#!/bin/bash
#
# ./zeta zk delete
#
# Remove ZK node or value
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$ZK_CONF"

reqshared "dockerregv2 zetaca openldap"

function _deletezk() {
    UNATTEND=0
    ZK_REF=""
    ZK_NODE=""
    SILENT="0"
    JSON="0"
    ZK_SRV=""
    RECURSE="0"
    for i in "$@"
    do
    case $i in
        "-j")
        JSON="1"
        ;;
        "-r")
        RECURSE="1"
        ;;
        "-s")
        SILENT="1"
        ;;
        "-u")
        UNATTEND="1"
        ;;
        "-c="*)
        ZK_SRV="${i#*=}"
        ;;
        "-z="*)
        ZK_REF="${i#*=}"
        ;;
        *)
        ZK_NODE="$i"
        # unknown option
    esac
    done
    if [ "$JSON" == "1" ]; then
        FORM="--format=json"
    else
        FORM="--format=txt"
    fi


    if [ "$ZK_REF" == "" ]; then
        if [ "$SILENT" == "0" ]; then
            @go.log INFO "No ZK_REF provided with -z=, using ZK_DEFAULT of $ZK_DEFAULT"
        fi
        ZK_REF="$ZK_DEFAULT"
    fi
    if [ "$ZK_NODE" == "" ]; then
        @go.log FATAL "Must pass a path/node to get ./zeta zk get /path/to/node"
    fi
    if [ "$ZK_BUILT" != "Y" ]; then
        @go.log FATAL "ZK not built - run ./zeta zk buildzk"
    fi

    . ${CLUSTERMOUNT}/zeta/kstore/env/zeta_shared.sh
    APP_IMG="$ZETA_DOCKER_REG_URL/zookeepercli:latest"

    if [ "$ZK_SRV" == "" ]; then
        ZK_REFVAR="ZK_${ZK_REF}"
        ZK_SRV="${!ZK_REFVAR}"
    else
        if [ "$SILENT" == "0" ]; then
            @go.log INFO "Using zookeeper string provided with -c"
        fi
    fi

    if [ "$RECURSE" == "1" ]; then
        CMD="rmr --force"
    else
        CMD="rm"
    fi

    if [ "$UNATTEND" != "1" ]; then
        @go.log WARN "Attempting to $CMD node $ZK_NODE from $ZK_SRV."
        read -e -p "Are you sure you wish to do this? (Y/N): " -i "N" CONFIRM
    else
        CONFIRM="Y"
    fi

    if [ "$CONFIRM" == "Y" ]; then
        sudo docker run --rm -it $APP_IMG --servers $ZK_SRV $FORM -c $CMD $ZK_NODE
    else
        @go.log FATAL "ZK RMR Action canceled by user"
    fi

}



_deletezk "$@"

