#!/bin/bash
#
# ./zeta zk get
#
# get ZK node or value
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$ZK_CONF"

reqshared "dockerregv2 zetaca openldap"

function _getzk() {
    ZK_REF=""
    ZK_NODE=""
    SILENT="0"
    JSON="0"

    for i in "$@"
    do
    case $i in
        "-j")
        JSON="1"
        ;;
        "-s")
        SILENT="1"
        ;;
        "-z="*)
        ZK_REF="${i#*=}"
        ;;
        *)
        ZK_NODE="$i"
        # unknown option
    esac
    done
    if [ "$JSON" == "1" ]; then
        FORM="--format=json"
    else
        FORM="--format=txt"
    fi


    if [ "$ZK_REF" == "" ]; then
        if [ "$SILENT" == "0" ]; then
            @go.log INFO "No ZK_REF provided with -z=, using ZK_DEFAULT of $ZK_DEFAULT"
        fi
        ZK_REF="$ZK_DEFAULT"
    fi
    if [ "$ZK_NODE" == "" ]; then
        @go.log FATAL "Must pass a path/node to get ./zeta zk get /path/to/node"
    fi
    if [ "$ZK_BUILT" != "Y" ]; then
        @go.log FATAL "ZK not built - run ./zeta zk buildzk"
    fi

    . /zeta/brewpot/zeta/kstore/env/zeta_shared.sh
    APP_IMG="$ZETA_DOCKER_REG_URL/zookeepercli:latest"

    ZK_REFVAR="ZK_${ZK_REF}"
    ZK_SRV="${!ZK_REFVAR}"
    sudo docker run --rm -it $APP_IMG --servers $ZK_SRV $FORM -c get $ZK_NODE

}



_listzk "$@"

