#!/bin/bash
#
# ./zeta zk list
#
# Lists ZK node
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$ZK_CONF"

reqshared "dockerregv2 zetaca openldap"

function _listzk() {
    ZK_REF=""
    ZK_SRV=""
    ZK_PATH=""
    SILENT="0"
    JSON="0"

    for i in "$@"
    do
    case $i in
        "-j")
        JSON="1"
        ;;
        "-s")
        SILENT="1"
        ;;
        "-c="*)
        ZK_SRV="${i#*=}"
        ;;
        "-z="*)
        ZK_REF="${i#*=}"
        ;;
        *)
        ZK_PATH="$i"
        # unknown option
    esac
    done

    if [ "$JSON" == "1" ]; then
        FORM="--format=json"
    else
        FORM="--format=txt"
    fi

    if [ "$ZK_REF" == "" ]; then
        if [ "$SILENT" == "0" ]; then
            @go.log INFO "No ZK_REF provided with -z=, using ZK_DEFAULT of $ZK_DEFAULT"
        fi
        ZK_REF="$ZK_DEFAULT"
    fi
    if [ "$ZK_PATH" == "" ]; then
        if [ "$SILENT" == "0" ]; then
            @go.log INFO "No ZK_PATH provided, using /"
        fi
        ZK_PATH="/"
    fi
    if [ "$ZK_BUILT" != "Y" ]; then
        @go.log FATAL "ZK not built - run ./zeta zk buildzk"
    fi

    . /zeta/brewpot/zeta/kstore/env/zeta_shared.sh
    APP_IMG="$ZETA_DOCKER_REG_URL/zookeepercli:latest"


    if [ "$ZK_SRV" == "" ]; then
        ZK_REFVAR="ZK_${ZK_REF}"
        ZK_SRV="${!ZK_REFVAR}"
    else
        if [ "$SILENT" == "0" ]; then
            @go.log INFO "Using zookeeper string provided with -c"
        fi
    fi
    sudo docker run --rm -it $APP_IMG --servers $ZK_SRV $FORM -c ls $ZK_PATH

}



_listzk "$@"

