#!/bin/bash
#
# Create conf file for initial DCOS installation
#

sourceconf "$PREP_CONF"

IP_DETECT="./conf/ip-detect"

ME=$(whoami)

if [ "$ME" != "$IUSER" ]; then
    @go.log FATAL "Currentling running as $ME. Scripts need to be run as $IUSER. Please connect to the init node as $IUSER via $ ssh -i $OUT_KEY $IUSER@$INIT_NODE"
fi


echo ""
echo "-----------------------------------"
echo "This process will ask a series of questions in order to create a dcos.conf script for gettings nodes ready for Zeta"
echo "The configuration will be located: $DCOS_CONF"
echo "-----------------------------------"
echo ""

./zeta dcos createipdetect "$IP_DETECT"

echo "---------------------------------------------"
echo "config.yaml"
echo "This next section will create a config.yaml for the DCOS install"
echo ""
echo "First the bootstrap node"
echo "There needs to be one node where the install files will be located. It will end up being an agent node, but first it needs to be the bootstrap node"
echo ""
echo "This is the current node list:"
echo ""
INTERNAL_NODES=""
for NODE in $NODES; do
    scp -o StrictHostKeyChecking=no $IP_DETECT $NODE:/tmp/ip-detect > /dev/null 2>&1
    INTERNAL=$(ssh -o StrictHostKeyChecking=no $NODE "/tmp/ip-detect" 2> /dev/null)
    INIT_N="N"
    if [ "$INTERNAL_NODES" == "" ]; then
       INTERNAL_NODES=""
    else
       INTERNAL_NODES="${INTERNAL_NODES} "
    fi
    INTERNAL_NODES="${INTERNAL_NODES}${INTERNAL}"

    if [ "$NODE" == "$INIT_NODE" ]; then
        INIT_N="Y"
        INIT_INTERNAL_IP="$INTERNAL"
    fi
    echo "Init: $INIT_N - External IP: $NODE - Internal_IP: $INTERNAL"
done
echo ""
echo ""
read -e -p "Please enter an IP (Internal) for the bootstrap node (default is init_node): " -i "$INIT_INTERNAL_IP" BOOTSTRAP_NODE
echo ""
read -e -p "Please enter the port to run the bootstrap server on, using defaults here is normally ok: " -i "50091" BOOTSTRAP_PORT
echo ""
echo ""
echo "Next is the list of master nodes:"
REMAINING_NODES=$(echo "$INTERNAL_NODES"|sed "s/$BOOTSTRAP_NODE//g")
echo "Picking an odd number of nodes is best. 1 for a test cluster. 3 For decent size clusters, 5 for large installations. This is difficult to change at a later time, 3 should be suffcient for most things"
echo "The list of remaining nodes is below, please enter the list of master nodes, separated by spaces"
echo ""
echo "$REMAINING_NODES"
echo
read -e -p "Please enter list of master node(s) using space to separate (Internal IPS): " MASTER_NODES
echo ""
echo ""
echo "At this point you can optionally enter public nodes. These nodes are given the slave_public role and are good for exposing services via a few nodes"
echo ""
echo "The remaining nodes you can pick from are:"
SOME_NODES="$REMAINING_NODES"
for N in $MASTER_NODES; do
    SOME_NODES=$(echo "$SOME_NODES"| sed "s/$N//g"|sed -e 's/^[ \t]*//'|sed -e 's/[ \t]*$//'|sed -r "s/ {2,}/ /g")
done

echo ""
echo "$SOME_NODES"
echo ""
read -e -p "Please enter a list of public node(s) using space to separate (Internal IPs) (Optional, just hit enter for none): " PUBLIC_NODES
echo ""
echo "Please enter a cluster name - This will match the clustername in MapR as well"
echo ""
read -e -p "Cluster name: " -i "mydcos" CLUSTERNAME
echo ""
echo "Please enter a POSIX client base mount point. This will be used, with the clustername as the basis for posix interaction with your shared filesystem"
echo ""
read -e -p "Cluster Mount point: " -i "zeta" CLUSTERBASE
echo ""
echo "Your cluster base is: $CLUSTERBASE"
echo "Your cluster name is: $CLUSTERNAME"
CLUSTERMOUNT="/$CLUSTERBASE/$CLUSTERNAME"
echo "Your cluster posix mount point is $CLUSTERMOUNT"
echo ""
echo "DNS Resolution"
echo "This is needed for external DNS resolution, defaults are examples from an AWS region, please enure the resolve it correct for your installation"
echo ""
echo "For assistance, here is your /etc/resolv.conf:"
echo ""
cat /etc/resolv.conf
echo ""
echo ""
read -e -p "Space separated list of DNS resolver IPs: " -i "172.31.0.2" DNS_RESOLVERS
echo ""
read -e -p "DNS Search base: " -i "us-west-2.compute.internal" DNS_SEARCH
echo ""

echo ""
echo "Cluster proxies. If your cluster needs HTTP_PROXY information to connect to the Internet, now is the time to enter that"
echo "We will ask for both Proxy information, as well as NOPROXY information"

echo ""
echo "---------------------------------------"
echo "If you need to specify a HTTP_PROXY for docker building, please enter it here"
echo "If this variable is filled, it will add the proxy lines to the docker files for building the images"
echo ""
read -p "Enter the proxy information (blank for none): " DOCKER_PROXY

echo ""
echo "---------------------------------------"
echo "If you need to specify a NO_PROXY string it's highly recommended. Use your subnets and internal domain names"
echo "Example: \"192.168.0.0/16,mycompany.com\""
echo ""
read -p "Enter the noproxy information (blank for none): " DOCKER_NOPROXY




AGENT_NODES="$INTERNAL_NODES"

for N in $MASTER_NODES; do
    AGENT_NODES=$(echo "$AGENT_NODES"| sed "s/$N//g"|sed -e 's/^[ \t]*//'|sed -e 's/[ \t]*$//'|sed -r "s/ {2,}/ /g")
done



cat > $DCOS_CONF << EOP
#!/bin/bash
DOCKER_PROXY="$DOCKER_PROXY"
DOCKER_NOPROXY="$DOCKER_NOPROXY"
CLUSTERBASE="$CLUSTERBASE"
CLUSTERNAME="$CLUSTERNAME"
CLUSTERMOUNT="$CLUSTERMOUNT"
MASTER_NODES="$MASTER_NODES"
BOOTSTRAP_NODE="$BOOTSTRAP_NODE"
BOOTSTRAP_PORT="$BOOTSTRAP_PORT"
BOOTSTRAP_LOC="/home/$IUSER/dcos_bootstrap"
DNS_RESOLVERS="$DNS_RESOLVERS"
DNS_SEARCH="$DNS_SEARCH"
INTERNAL_NODES="$INTERNAL_NODES"
AGENT_NODES="$AGENT_NODES"
PUBLIC_NODES="$PUBLIC_NODES"
INIT_INTERNAL_IP="$INIT_INTERNAL_IP"
DCOS_LOCKED="1"
IP_DETECT="$IP_DETECT"

EOP


