#!/bin/bash
#
# sshhosts
#
# A helper script to add ssh host keys to the init node 
#
# Arguments - None
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"

function _addsshhosts() {

    INTERNAL_HN=""
    INTERNAL_FQHN=""
    echo "This script connects and allows you to trust the keys of the SSH hosts"
    echo "It runs through the nodes three times, one for the Internal IPs, one for the hostsname, and one for the full host names so that the keys can be trusted for each of the three"
    echo ""
    echo ""
    echo "Connecting by IP to get hostnames - Answer yes"
    for IP in $INTERNAL_NODES; do
        HN=$(ssh $IP hostname)
        if [ "$INTERNAL_HN" == "" ]; then
            INTERNAL_HN="$HN"
        else
            INTERNAL_HN="${INTERNAL_HN} $HN"
        fi
    done

    echo ""
    echo "Connecting by hostname to get the fully qualified - Answer yes"
    for HN in $INTERNAL_HN; do
        FQHN=$(ssh $HN "hostname -f")
        if [ "$INTERNAL_FQHN" == "" ]; then
            INTERNAL_FQHN="$FQHN"
        else
            INTERNAL_FQHN="${INTERNAL_FQHN} $FQHN"
        fi
    done

    echo ""
    echo "Connecting by FQHNs to trust them - Answer yes"
    for FQHN in $INTERNAL_FQHN; do
        ssh $FQHN "hostname -f"
    done

}


_addsshhosts "$@"

