#!/bin/bash
#
# adds the shared role to Zeta Schemas 
# No Arguments, just adds the shared role
#
sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"


reqshared "dockerregv2 zetaca openldap"


function _displayhelp(){
    echo "cluster addsharedrole - Creates a new role for shared services"
    echo "===================================================================================================="
    echo ""
    echo "Arguments:"
    echo "-h               - Display this help"
    echo ""
    echo "Usage:"
    echo "./zeta cluster addsharedrole"
    echo ""
}

function _addsharedrole() {

    DISPLAYHELP="0"
    for i in "$@"
        do
        case $i in
            -h)
            DISPLAYHELP="1"
            ;;
            *)
            # unknown option
            ;;
        esac
    done
    if [ "$DISPLAYHELP" == "1" ]; then
        _displayhelp
        exit 0
    fi


    @go.log INFO "Adding shared role to Zeta"
    ./zeta users roleschema -a -r="shared" -u

    MYDIRS=$(echo "$ROOT_DIRS"|tr "," " ")
    for DIR in $MYDIRS; do
        @go.log INFO "Updating permissions on Shared $DIR Directory"
        sudo chown -R $IUSER:zetashared${DIR} ${CLUSTERMOUNT}/${DIR}/shared
    done
}
_addsharedrole "$@"
