#!/bin/bash
#
# Scripts for working with marathon
#

function _marathon() {

    echo "Commands to use with cluster marathon:"
    echo ""
    echo "./zeta cluster marathon submit - Submit a marathon file (first argument) to marathon url (second argument)"
    echo ""
}

_marathon "$@"
