#!/bin/bash
#
# cluster zetabase
#
# Base Directory installation for Zeta Architecture
#
#
sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"


FS_LIB="lib${FS_PROVIDER}"
. "$_GO_USE_MODULES" $FS_LIB

function _zetabase() {

    CURUSER=$(whoami)
    if [ "$CURUSER" != "$IUSER" ]; then
        @go.log FATAL "Must use $IUSER user"
    fi

    if [ -f "$CLUSTER_BASE_CONF" ]; then
        @go.log FATAL "Cluster base conf found at $CLUSTER_BASE_CONF - Not installing"
    fi

    # Run FS Provider specific prep (cleaning) 
    fs_prepbase


    if [ ! -d "$CLUSTERMOUNT/user" ]; then
        mkdir -p $CLUSTERMOUNT/user # Just a need a directory here
    fi

   @go.log INFO "Checking for and creating if not existing, home directories for $FSUSER and $IUSER users"
    UNAMES="$FSUSER $IUSER"
    for U in $UNAMES; do
        if [ ! -d "$CLUSTERMOUNT/user/$U" ]; then
            @go.log INFO "User Directory for $U not found: Creating"
            fs_mkvol "RETCODE" "/user/$U" "user.$U" "770"
            sudo chown -R $U:${IUSER} $CLUSTERMOUNT/user/$U
        else
            @go.log INFO "User directory for $U found"
        fi
    done


    @go.log INFO "Creating root directories for your zeta cluster"
    ROOTS=$(echo $ROOT_DIRS|tr "," " ")
    for DIR in $ROOTS; do
        if [ -d "$CLUSTERMOUNT/$DIR" ]; then
            @go.log WARN "Directory $CLUSTERMOUNT/$DIR already exists: Updating Permissions"
        else
            @go.log INFO "Creating directory $CLUSRERMOUNT/$DIR and updating permissions"
            sudo mkdir -p $CLUSTERMOUNT/$DIR
        fi
        sudo chown -R ${IUSER}:2501 $CLUSTERMOUNT/$DIR
        sudo chmod -R 750 $CLUSTERMOUNT/$DIR
    done

    exit 0
    #####################################################
    # Create base Zeta Key Store locations
    # the kstore directory under zeta is used to house zeta specific configuration data, as well as zeta specific clusterwide information
    # Descriptions of the locations are below
    @go.log INFO "Setting up zeta kstore directory"
    DIR="$CLUSTERMOUNT/zeta/kstore"
    sudo mkdir -p $DIR
    sudo chown ${IUSER}:2501 $DIR
    sudo chmod 755 $DIR

    # Group Sync
    DIR="$CLUSTERMOUNT/zeta/kstore/zetasync"
    sudo mkdir -p $DIR
    sudo chown ${IUSER}:${IUSER} $DIR
    sudo chmod 775 $DIR

    if [ ! -f "$DIR/zetagroups.list" ]; then
cat > ${DIR}/zetagroups.list << GRPEOF
GRPEOF
    else
        @go.log WARN "Not clobbering exiting zetagroups.list"
    fi
    if [ ! -f "$DIR/zetausers.list" ]; then
cat > ${DIR}/zetausers.list << USROF
USROF
    else
        @go.log WARN "Not clobbering exiting zetausers.list"
    fi

    if [ ! -f "$DIR/zetauid.list" ]; then
        touch ${DIR}/zetauid.list
    else
        @go.log WARN "Not clobbering exiting zetauid.list"
    fi

    # ENV Main
    DIR="$CLUSTERMOUNT/zeta/kstore/env"
    sudo mkdir -p $DIR
    sudo chown ${IUSER}:${IUSER} $DIR
    sudo chmod 775 $DIR

    if [ ! -f "$DIR/master_env.sh" ]; then
    @go.log INFO "Building Zeta Master ENV File"
cat > $DIR/master_env.sh << EOL3
#!/bin/bash

# START GLOBAL ENV Variables for Zeta Environment

export ZETA_CLUSTERNAME="${CLUSTERNAME}"
export ZETA_NFS_ROOT="$CLUSTERMOUNT"

export ZETA_MESOS_DOMAIN="mesos"
export ZETA_MESOS_LEADER="leader.\${ZETA_MESOS_DOMAIN}"
export ZETA_MESOS_LEADER_PORT="5050"

# END GLOBAL ENV VARIABLES
EOL3
    else
        @go.log WARN "Not clobbering existing master_env.sh"
    fi


    ##########
    # Installing global role directories
    # This is only available to $IUSER and is used for shared services like a cluster wide docker registry, and cluster wide ldap server
    #
    @go.log INFO "Looking for shared directory (volume) in each root direcory, create if not found"
    for DIR in $ROOTS; do
        if [ -d "$CLUSTERMOUNT/$DIR/shared" ]; then
            @go.log WARN "$CLUSTERMOUNT/$DIR/shared already exists, skipping"
        else
            @go.log INFO "Creating $CLUSTERMOUNT/$DIR/shared"
            fs_mkvol "RETCODE" "/$DIR/shared" "$DIR.shared" "770"
            sudo chown -R ${IUSER}:${IUSER} $CLUSTERMOUNT/$DIR/shared
        fi
    done

    DIR="$CLUSTERMOUNT/zeta/kstore/env/env_shared"
    sudo mkdir -p $DIR
    sudo chown ${IUSER}:${IUSER} $DIR
    sudo chmod 775 $DIR
    ENV_FILE="$CLUSTERMOUNT/zeta/kstore/env/zeta_shared.sh"

cat > $ENV_FILE << EOL9
# Source Master Zeta ENV File
. $CLUSTERMOUNT/zeta/kstore/env/master_env.sh

# START GLOBAL ENV Variables for Zeta Environment

export ZETA_MARATHON_ENV="marathon"
export ZETA_MARATHON_HOST="\${ZETA_MARATHON_ENV}.\${ZETA_MESOS_DOMAIN}"
export ZETA_MARATHON_PORT="8080"
export ZETA_MARATHON_URL="\$ZETA_MARATHON_HOST:\$ZETA_MARATHON_PORT"
export ZETA_MARATHON_SUBMIT="http://\$ZETA_MARATHON_URL/v2/apps"
export ZETA_CLDBS="$CLDBS"
export ZETA_IUSER="$IUSER"
export ZETA_ZKS="$ZKS"
export ZETA_DOCKER_PROXY="$DOCKER_PROXY"

# Source env_shared
for SRC in $CLUSTERMOUNT/zeta/kstore/env/env_shared/*.sh; do
   . \$SRC
done

if [ "\$1" == "1" ]; then
    env|grep -P "^ZETA_"
fi

EOL9

    chmod +x $ENV_FILE
    #Create a dummy script in the env_prod directory so that file not found errors don't appear when sourcing main file
cat > $CLUSTERMOUNT/zeta/kstore/env/env_shared/env_shared.sh << EOL5
#!/bin/bash
# Basic script to keep file not found errors from happening
EOL5

    @go.log INFO "Base Zeta Cluster layout installed"

cat > "$CLUSTER_BASE_CONF" << EO7
#!/bin/bash
# Base Layout installed
EO7

}

_zetabase "$@"
