#!/bin/bash
#
# cluster zetaca - Scripts to stage and run Zeta CA Shared service
##

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$MAPR_CONF"
sourceconf "$CLUSTER_CONF"

function _zetaca() {

    LOCK="0"

    for i in "$@"
    do
        case $i in
            -l)
            LOCK="1"
            ;;
            *)
            # unknown option
            ;;
        esac
    done

    initconf "$CLUSTER_ZETACA_CONF"

    echo ""
    echo "********************************"
    echo "Scripts should now be run on cluster"
    echo "That should be: $INIT_NODE"
    echo "********************************"
    echo ""
    echo "Commands to use with cluster zetaca:"
    echo "./zeta cluster zetaca install - Build and install Zeta CA - Update all hosts as well"
    echo "./zeta cluster zetaca updatenode -  (-a for all nodes, or CSV list of nodes for specific nodes) -u for unattended"
    echo ""
    echo "Helper Functions: (Not normally needed to be called on their own)"
    echo "./zeta cluster zetaca build - Build the Zetaca Docker container based on conf file"
    echo "./zeta cluster zetaca final - After Zeta base is installed, move zetaca from tmp local location to clustered location (only need to run once)"
    echo ""
    echo "Config Management:"
    echo "./zeta cluster zetaca -l - lock or unlock cluster_zetaca.conf file"
    echo ""


    if [ "$LOCK" == "1" ]; then
       lockconf "$CLUSTER_ZETACA_CONF"
    fi

}

_zetaca "$@"

