#!/bin/bash
#
# installzk
#
# A Script to install the helper script to add ssh host keys to the init node
#
# Arguments - None
#

sourceconf "$PREP_CONF"
sourceconf "$MESOS_CONF"
sourceconf "$NETWORK_CONF"

function _installzk() {

    UNATTEND="0"
    for i in "$@"
       do
        case $i in
             -u)
             UNATTEND="1"
             ;;
            "-n="*)
            HOST="${i#*=}"
            ;;
            *)
            # unknown option
            ;;
        esac
    done

    if [ "$HOST" == "" ]; then
        RUN_NODES="$MASTER_NODES"
    else
        RUN_NODES="$HOST"
    fi

    .  ./vers/mesos/$ZK_VERS

    ZK_SERVERS=""
    ZK_CNT="0"
    for N in $MASTER_NODES; do
        if [ "$ZK_SERVERS" == "" ]; then
            ZK_SERVERS="server.${ZK_CNT}=${N}:3888:2888"$'\n'
        else
            ZK_SERVERS="${ZK_SERVERS}server.${ZK_CNT}=${N}:3888:2888"$'\n'
        fi
        ZK_CNT=$(($ZK_CNT+1))
    done


cat > ./bin/zk_install.sh << EOZ
#!/bin/bash
echo "Creating Directories"
sudo mkdir -p $ZETA_MESOS_DIR/zookeeper/data
sudo mkdir -p $ZETA_MESOS_DIR/zookeeper/datalog
sudo mkdir -p $ZETA_MESOS_DIR/zookeeper/log
sudo mkdir -p $ZETA_MESOS_DIR/zookeeper/conf
sudo chown -R $IUSER:$IUSER $ZETA_MESOS_DIR/
sudo chmod 775 $ZETA_MESOS_DIR
sudo chmod 770 $ZETA_MESOS_DIR/zookeeper
sudo chmod 777 $ZETA_MESOS_DIR/zookeeper/log
sudo cp /home/$IUSER/ip-detect $ZETA_MESOS_DIR/
sudo chmod +x $ZETA_MESOS_DIR/ip-detect

echo "Getting Default Files"
sudo docker pull $MESOS_ZK_IMG
CID=\$(sudo docker run -d $MESOS_ZK_IMG sleep 30)
sudo docker cp \$CID:/conf/ $ZETA_MESOS_DIR/zookeeper/
sudo docker stop \$CID
sudo docker rm \$CID
sudo chown -R ${IUSER}:${IUSER} $ZETA_MESOS_DIR/zookeeper

echo "Creating mesos-zookeeper.service"
cat > $ZETA_MESOS_DIR/zookeeper/mesos-zookeeper.service << EOS
[Unit]
Description=Zookeeper Node for Mesos on Zeta
Requires=docker.service
After=docker.service

[Service]
Restart=on-failure
ExecStartPre=-/usr/bin/docker stop zookeeper
ExecStartPre=-/usr/bin/docker rm -f zookeeper
ExecStart=/usr/bin/docker run --rm -e ZOO_LOG_DIR="/log" -v $ZETA_MESOS_DIR/zookeeper/data:/data:rw -v $ZETA_MESOS_DIR/zookeeper/log:/log:rw -v $ZETA_MESOS_DIR/zookeeper/datalog:/datalog:rw -v $ZETA_MESOS_DIR/zookeeper/conf:/conf:rw --name zookeeper --net=HOST $MESOS_ZK_IMG
ExecStop=/usr/bin/docker stop -t 2 zookeeper

[Install]
WantedBy=multi-user.target

EOS
echo "Updating logging dirs"
sed -i "s@zookeeper\.log\.dir=\.@zookeeper.log.dir=/log@" $ZETA_MESOS_DIR/zookeeper/conf/log4j.properties
sed -i "s@zookeeper\.tracelog\.dir=\.@zookeeper.tracelog.dir=/log@" $ZETA_MESOS_DIR/zookeeper/conf/log4j.properties
sed -i "s/zookeeper\.root\.logger=.*/zookeeper.root.logger=ROLLINGFILE,INFO,CONSOLE/" $ZETA_MESOS_DIR/zookeeper/conf/log4j.properties
sed -i "s/#log4j\.rootLogger=DEBUG, CONSOLE, ROLLINGFILE/log4j.rootLogger=DEBUG, CONSOLE, ROLLINGFILE/" $ZETA_MESOS_DIR/zookeeper/conf/log4j.properties

echo "Creating zoo.cfg"
cat > $ZETA_MESOS_DIR/zookeeper/conf/zoo.cfg << EOC
# The number of milliseconds of each tick
tickTime=2000
# The number of ticks that the initial
# synchronization phase can take
initLimit=20
# The number of ticks that can pass between
# sending a request and getting an acknowledgement
syncLimit=10
# the directory where the snapshot is stored.
dataDir=/data
# The Data log directory
dataLogDir=/datalog
# the port at which the clients will connect
clientPort=2181
# max number of client connections
maxClientCnxns=100
#readuser to allow read zk info for authenticated clients
readUser=anyone
$ZK_SERVERS
EOC

echo "Updating the myid"
MYIP=\$($ZETA_MESOS_DIR/ip-detect)
MYID=\$(cat $ZETA_MESOS_DIR/zookeeper/conf/zoo.cfg|grep "\$MYIP"|cut -d"=" -f1|cut -d"." -f2)
echo "\$MYID" > $ZETA_MESOS_DIR/zookeeper/data/myid

echo "Adding systemd service"
sudo cp $ZETA_MESOS_DIR/zookeeper/mesos-zookeeper.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl start mesos-zookeeper.service
sudo systemctl enable mesos-zookeeper.service
EOZ

    chmod +x ./bin/zk_install.sh
    for IP in $RUN_NODES; do
        scp ./bin/zk_install.sh $IP:/home/$IUSER/
        scp ./conf/ip-detect $IP:/home/$IUSER/
        ssh $IP "/home/$IUSER/zk_install.sh"
    done

}


_installzk "$@"

