#!/bin/bash
#
# mapr fuseinstall - Install MapR Fuse client on single node
#
# Arguments:
# -u - Unattended
# -n=%NODE%  %NODE% being the node to install on
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"

. ./vers/mapr/$MAPR_VERS

MYDIR=$(pwd)

MEUSER=$(whoami)

if [ "$MEUSER" != "${IUSER}" ]; then
    @go.log FATAL "This script needs to be un as ${IUSER}. Current User: $MEUSER"
fi


function _fuseinstall() {


    UNATTEND="0"
    NODE_HOST=""

    for i in "$@"
        do
        case $i in
            -u)
            UNATTEND="1"
            ;;
            "-n="*)
            NODE_HOST="${i#*=}"
            ;;
            *)
            # unknown option
            ;;
        esac
    done



    if [ "$NODE_HOST" == "" ]; then
        @go.log FATAL "This script must be passed a hostname via the -n= parameter Ex: -n=node1"
    fi

    NETTEST=$(ssh $NODE_HOST hostname)

    if [ "$NETTEST" == "" ]; then
        @go.log FATAL "Cannot connect to host $NODE_HOST for fuse install"
    fi


    if [ "$MAPR_SECURE" == "1" ]; then
        if [ ! -f "./conf/secmapr/fuseticket" ]; then
            @go.log WARN "It appears you are running a secure cluster without the initial mapr ticket generated (for the mapr user)"
            read -e -p "Do you wish to generate that ticket? (Y/N): " -i "Y" GENTICK
            if [ "$GENTICK" != "Y" ]; then
                @go.log FATAL "Cannot proceed with install due to a lack of MapR Ticket"
            fi
            DCHK=$(sudo docker ps|grep maprdocker|cut -d" " -f1)
            if [ "$DCHK" == "" ]; then
                @go.log FATAL "Could not find MapR image running on this node"
            fi
            @go.log INFO "Logging into to cluster to generate service Ticket"
            sudo docker exec -it $DCHK su -c "maprlogin password -duration 86400" mapr
            @go.log INFO "Generating Service Ticket"
            sudo docker exec -it $DCHK su -c "maprlogin generateticket -type service -out /tmp/fuseticket -duration 180:0:0 -renewal 365:0:0" mapr
            sudo docker cp $DCHK:/tmp/fuseticket ./conf/secmapr/
            sudo docker exec -it $DCHK rm /tmp/fuseticket
            sudo chown ${IUSER}:${IUSER} ./conf/secmapr/fuseticket
        fi
    fi



    # Need to update for Cent/RH detection We are only detecting Ubuntu right now
    DIST=$(ssh $NODE_HOST "grep DISTRIB_ID /etc/lsb-release")


    UBUNTU_CHK=$(echo $DIST|grep Ubuntu)

    if [ "$UBUNTU_CHK" != "" ]; then
        INST_DIST="ubuntu"
    else
        @go.log FATAL "Not an ubuntu host - we only install on ubuntu for now"
    fi

    CURCHK=$(ssh $NODE_HOST "ls /opt/mapr 2> /dev/null")

    if [ "$CURCHK" != "" ]; then
        @go.log FATAL "/opt/mapr identified, node not clean, will not install"
    fi

    if [ "$UNATTEND" != "1" ]; then
        echo "Installation requested on $NODE_HOST (Ubuntu) - No Previous Installation Detected"
        read -p "Continue with install? " -e -i "N" CONT
    else
        CONT="Y"
    fi

    if [ "$CONT" != "Y" ]; then
        @go.log FATAL "Installation aborted by user"
    fi
    @go.log INFO "Installing MapR FUSE client on $NODE_HOST"

    JV=$(ssh $NODE_HOST "grep JAVA_HOME /etc/environment")
    if [ "$JV" == "" ]; then
        @go.log INFO "JAVA_HOME not found in /etc/environment on $NODE_HOST - Setting to /opt/mesosphere/active/java/usr/java"
        ssh $NODE_HOST "echo \"JAVA_HOME=/opt/mesosphere/active/java/usr/java\"|sudo tee -a /etc/environment"
    fi

    CLIENT_DIR="./bin/client_install"

    mkdir -p $CLIENT_DIR

    if [ "$INST_DIST" == "ubuntu" ]; then
        if [ ! -f "${CLIENT_DIR}/$UBUNTU_MAPR_CLIENT_FILE" ] || [ ! -f "${CLIENT_DIR}/$UBUNTU_MAPR_POSIX_FILE" ]; then
            echo "Couldn't find MapR Files"
            @go.log WARN "MapR Client Install files not found"

            if [ "$UNATTEND" != "1" ]; then
                read -p "Should we Download the Ubuntu files? (Installation will not continue if N) " -e -i "Y" DL
            else
                DL="Y"
            fi
            if [ "$DL" != "Y" ]; then
                @go.log FATAL "Cannot continue without install files - exiting"
            fi
            @go.log INFO "Downloading MapR Install files"
            cd $CLIENT_DIR
            wget ${UBUNTU_MAPR_CLIENT_BASE}${UBUNTU_MAPR_CLIENT_FILE}
            wget ${UBUNTU_MAPR_POSIX_BASE}${UBUNTU_MAPR_POSIX_FILE}
            if [ "$UBUNTU_MAPR_PATCH_CLIENT_FILE" != "" ]; then
                wget ${UBUNTU_MAPR_PATCH_BASE}${UBUNTU_MAPR_PATCH_CLIENT_FILE}
                wget ${UBUNTU_MAPR_PATCH_BASE}${UBUNTU_MAPR_PATCH_POSIX_FILE}
            fi
            cd $MYDIR
        fi
        INST_CLIENT=$UBUNTU_MAPR_CLIENT_FILE
        INST_POSIX=$UBUNTU_MAPR_POSIX_FILE
        INST_CMD="dpkg -i"
    elif [ "$INST_DIST" == "rh" ]; then
        @go.log FATAL "Redhat/CentOS not setup at this time"

        INST_CLIENT=$RH_MAPR_CLIENT_FILE
        INST_POSIX=$RH_MAPR_POSIX_FILE
        INST_CMD="rpm -ivh"
    fi

    scp ${CLIENT_DIR}/$INST_CLIENT $NODE_HOST:/home/${IUSER}/
    scp ${CLIENT_DIR}/$INST_POSIX $NODE_HOST:/home/${IUSER}/

    if [ "$UBUNTU_MAPR_PATCH_CLIENT_FILE" != "" ]; then
        scp ${CLIENT_DIR}/${UBUNTU_MAPR_PATCH_CLIENT_FILE} $NODE_HOST:/home/${IUSER}/
        scp ${CLIENT_DIR}/${UBUNTU_MAPR_PATCH_POSIX_FILE} $NODE_HOST:/home/${IUSER}/
    fi

    ssh $NODE_HOST "sudo $INST_CMD $INST_CLIENT"
    if [ "$UBUNTU_MAPR_PATCH_CLIENT_FILE" != "" ]; then
        ssh $NODE_HOST "sudo $INST_CMD ${UBUNTU_MAPR_PATCH_CLIENT_FILE}"
    fi
tee /tmp/fs_core.xml << EOL1
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<!--
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License. See accompanying LICENSE file.
-->

<!-- Put site-specific property overrides in this file. -->
<configuration>
  <property>
    <name>fs.mapr.shmpool.size</name>
    <value>0</value>
  </property>
</configuration>
EOL1

    scp /tmp/fs_core.xml $NODE_HOST:/home/${IUSER}/

    rm /tmp/fs_core.xml

    CORE_DST="/opt/mapr/hadoop/hadoop-2.7.0/etc/hadoop/core-site.xml"

    ssh $NODE_HOST "sudo mv /home/${IUSER}/fs_core.xml $CORE_DST && sudo chown mapr:root $CORE_DST && sudo chmod 644 $CORE_DST"


    NSUB="export MAPR_SUBNETS=$SUBNETS"
    ssh $NODE_HOST "sudo sed -i -r \"s@#export MAPR_SUBNETS=.*@${NSUB}@g\" /opt/mapr/conf/env.sh"
    ssh $NODE_HOST "echo \"$NODE_HOST-fuse\"|sudo tee /opt/mapr/hostname"
    if [ "$MAPR_SECURE" == "1" ]; then
        @go.log WARN "Setting MapR Secure and copying truststore"
        scp ./conf/secmapr/ssl_truststore ${IUSER}@${NODE_HOST}:/home/${IUSER}/
        ssh $NODE_HOST "sudo mv /home/${IUSER}/ssl_truststore /opt/mapr/conf/ && sudo chmod 664 /opt/mapr/conf/ssl_truststore && sudo mkdir -p /opt/mapr/conf/mapr_tickets"
        scp ./conf/secmapr/fuseticket ${IUSER}@${NODE_HOST}:/home/${IUSER}/
        ssh ${NODE_HOST} "sudo mv /home/${IUSER}/fuseticket /opt/mapr/conf/mapr_tickets/ && sudo chown ${FSUSER}:${FSUSER} /opt/mapr/conf/mapr_tickets/fuseticket && sudo chmod 600 /opt/mapr/conf/mapr_tickets/fuseticket"
        MSEC="-secure"
    else
        @go.log INFO "Non-Secure Cluster Install"
        MSEC=""
    fi
    ssh $NODE_HOST "sudo /opt/mapr/server/configure.sh -N $CLUSTERNAME -c -C $CLDBS $MSEC"
    ssh $NODE_HOST "sudo mkdir -p /$CLUSTERBASE"
    ssh $NODE_HOST "sudo $INST_CMD $INST_POSIX"
    if [ "$MAPR_SECURE" == "1" ]; then
        ssh ${NODE_HOST} "sudo sed -i -e 's@#fuse\.ticketfile\.location=.*\$@fuse.ticketfile.location=/opt/mapr/conf/mapr_tickets/fuseticket@g' /opt/mapr/conf/fuse.conf"
    fi

    if [ "$UBUNTU_MAPR_PATCH_POSIX_FILE" != "" ]; then
        ssh $NODE_HOST "sudo $INST_CMD ${UBUNTU_MAPR_PATCH_POSIX_FILE}"
    fi



    ssh $NODE_HOST "echo \". /opt/mapr/conf/env.sh\"|sudo tee -a /opt/mapr/initscripts/mapr-posix-client-basic"

    ssh $NODE_HOST "sudo sed -i '/# Look for installed JDK/ i . \${BASEMAPR}/conf/env.sh' /opt/mapr/initscripts/mapr-fuse"
    ssh $NODE_HOST "sudo sed -i 's@fuse\.mount\.point=/mapr@fuse.mount.point=/$CLUSTERBASE@g' /opt/mapr/conf/fuse.conf"
    ssh $NODE_HOST "sudo /etc/init.d/mapr-posix-client-basic start"
    echo "NFS Mount: "
    ssh $NODE_HOST "ls -ls $CLUSTERMOUNT"

    echo ""
    echo "Installed - ls $CLUSTERMOUNT"
    echo ""
    echo "hadoop fs:"
    ssh $NODE_HOST "hadoop fs -ls /"
}

_fuseinstall "$@"
