#!/bin/bash
#
# Zeta Main Script
#

declare -r __GO_CORE="${0%/*}/scripts/go-script-bash/go-core.bash"

BASE_CONF="./conf/base.conf"

if [ ! -f "$BASE_CONF" ]; then
    echo "Creating Initial Confing in $BASE_CONF"
cat > $BASE_CONF << EOF
#!/bin/bash

export PREP_CONF="./conf/prep.conf"
export DCOS_CONF="./conf/dcos.conf"
export MAPR_CONF="./conf/mapr.conf"
export CLUSTER_CONF="./conf/cluster.conf"
export CLUSTER_ZETACA_CONF="./conf/cluster_zetaca.conf"
export CLUSTER_BASE_CONF="./conf/cluster_base.conf"
export PACKAGE_CONF="./conf/package.conf"
export NETWORK_CONF="./conf/network.conf"
EOF
fi
. $BASE_CONF

if [[ ! -f "$__GO_CORE" ]]; then
  git submodule update --init
fi
. "$__GO_CORE" "scripts"
. "$_GO_USE_MODULES" 'log'
. "$_GO_USE_MODULES" 'libcommon'

@go "$@"



