#!/bin/bash
#
# Create conf file for node management
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"

reqshared "dockerregv2 zetaca openldap"


cat > $NODE_CONF << EON
#!/bin/bash

NODE_LOCKED="1"
EON

@go.log INFO "Node Management conf created at $NODE_CONF"

