#!/bin/bash
#
# Show Status of Roles in Zeta ENV
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$NODE_CONF"
sourceconf "$ROLE_CONF"

reqshared "dockerregv2 zetaca openldap"


function _rolestatus() {

    echo "Role Status Comming soon"

    CUR_STATUS=$(curl -s http://leader.mesos:5050/master/slaves)


    #Pretty print json
#    echo "$CUR_STATUS"| jq .


    # Print the type
#    echo "$CUR_STATUS"|jq type

    # Prints all the hostsnames
      echo "$CUR_STATUS" | jq '.[]|.[]|.'

    HOSTS=$( echo "$CUR_STATUS" | jq -r '.[]|.[]|.hostname' )

    for HOST in $HOSTS; do
        echo "HOST: $HOST"
        echo "$CUR_STATUS" | jq --arg hn "$HOST" '.[]|.[]|select(.hostname==$hn)|.resources'
    done


}

_rolestatus "$@"
