#!/bin/bash
#
# Show Status of Roles in Zeta ENV
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$NODE_CONF"
sourceconf "$ROLE_CONF"

reqshared "dockerregv2 zetaca openldap"


function _rolestatus() {

    echo "Role Status Comming soon"

}

_rolestatus "$@"
