#!/bin/bash
#
# Create conf file for Zeta zetaca installation
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$MAPR_CONF"
sourceconf "$CLUSTER_CONF"

ZETACA_HOME="/home/${IUSER}/zetaca"

mkdir -p $ZETACA_HOME
mkdir -p $ZETACA_HOME/CA
sudo chown -R ${IUSER}:${IUSER} $ZETACA_HOME
sudo chmod 775 $ZETACA_HOME
sudo chmod 700 $ZETACA_HOME/CA
@go.log INFO "Zeta CA Home set to $ZETACA_HOME and this directory is created and secured"


# Now we will run the docker container to create the CA for Zeta
# Note: Both this script and the git repo script should be changed so we can write the password to a secure file in $APP_HOME/certs/ca_key.txt 
# And the script that instantiates the CA reads the value from the file rather than passing it as an argument that will appear in process listing 

echo ""
echo "Please select a version file to use for zeta ca:"
echo ""
ls ./vers/zetaca
echo ""
read -e -p "Zeta ca version file: " -i "zetaca-1.0.0.vers" ZETACA_VERS

echo ""
. ./vers/zetaca/${ZETACA_VERS}
echo ""
echo ""
ZETACA_IP=$(./conf/ip-detect)
echo "The IP Address of this host is where we recommend running the zetaca, that IP is $ZETACA_IP"
echo ""

PORTSTR="CLUSTER:tcp:10443:shared:zetaca:Zeta CA Rest API Service"
getport "CHKADD" "Please enter the port for the Zeta CA Rest service to run on: " "$SERVICES_CONF" "$PORTSTR" "1"

if [ "$CHKADD" != "" ]; then
    getpstr "TYPE" "PROTOCOL" "APP_PORT" "ROLE" "APP_ID" "COMMENTS" "$CHKADD"
    APP_PORTSTR="$CHKADD"
else
    @go.log FATAL "Adding Porting to services failed $PSTR"
fi



echo ""
echo "We need some information for the CA Certificate - You can accept defaults, or choose your own for your setup"
echo "In addition, we may ask if you want to use the CA Certificate value for defaults for other certificates generated, you can always override values on the server certs, but defaults help make things go faster"
echo ""
echo "Remember: "
echo "CA Certificate = The Information on the Certificate for the Certificate Authority"
echo "Default Certificate = A recommened (and overridable) value for use in creating server certificates later"
echo ""
read -e -p "CA Certificate Country (C): " -i "US" CACERT_C
echo ""
read -e -p "Default Certificate Country (C) for generated certificates: " -i $CACERT_C CERT_C
echo ""
read -e -p "CA Certificate State (ST): " -i "WI" CACERT_ST
echo ""
read -e -p "Default Certificate State (ST) for generated certificates: " -i $CACERT_ST CERT_ST
echo ""
read -e -p "CA Certificate Location (L): " -i "Wittenberg" CACERT_L
echo ""
read -e -p "Default Certificate Location (L) for generated certificates: " -i $CACERT_L CERT_L
echo ""
read -e -p "CA Certificate Organization (O): " -i "OIT" CACERT_O
echo ""
read -e -p "Default Certificate Organization (O) for generated certificates: " -i $CACERT_O CERT_O
echo ""
read -e -p "CA Certificate Organizational Unit (OU): " -i "Zeta" CACERT_OU
echo ""
read -e -p "Default Certificate Organizational Unit (OU) for generated certificates: " -i $CACERT_OU CERT_OU
echo ""
read -e -p "CA Certificate Common Name (CN): " -i "marathon.mesos" CACERT_CN
echo ""
echo "The Common Name for Certificates will be determined at certificate generation"
echo ""
CERT_CN="marathon.mesos"





cat > ${ZETACA_HOME}/zetaca_env.sh << EOA
#!/bin/bash
export ZETA_CERT_C="$CERT_C"
export ZETA_CERT_ST="$CERT_ST"
export ZETA_CERT_L="$CERT_L"
export ZETA_CERT_O="$CERT_O"
export ZETA_CERT_OU="$CERT_OU"
export ZETA_CERT_CN="$CERT_CN"

export ZETA_CA_PORT="$APP_PORT"
export ZETA_CA="http://zetaca-shared.marathon.slave.mesos:$APP_PORT"
export ZETA_CA_CERT="\${ZETA_CA}/cacert"
export ZETA_CA_CSR="\${ZETA_CA}/csr"
EOA

cat > $CLUSTER_ZETACA_CONF << EOF
#!/bin/bash
export ZETACA_IP="$ZETACA_IP"
export ZETACA_VERS="$ZETACA_VERS"
export ZETACA_HOME="$ZETACA_HOME"
export ZETACA_IMG="$APP_IMG"
export ZETA_CACERT_C="$CACERT_C"
export ZETA_CACERT_ST="$CACERT_ST"
export ZETA_CACERT_L="$CACERT_L"
export ZETA_CACERT_O="$CACERT_O"
export ZETA_CACERT_OU="$CACERT_OU"
export ZETA_CACERT_CN="$CACERT_CN"

export ZETA_CERT_C="$CERT_C"
export ZETA_CERT_ST="$CERT_ST"
export ZETA_CERT_L="$CERT_L"
export ZETA_CERT_O="$CERT_O"
export ZETA_CERT_OU="$CERT_OU"
export ZETA_CERT_CN="$CERT_CN"

export ZETA_CA_PORTSTR="$APP_PORTSTR"
export ZETA_CA_PORT="$APP_PORT"
export ZETA_CA="http://zetaca-shared.marathon.slave.mesos:$APP_PORT"
export ZETA_CA_CERT="\${ZETA_CA}/cacert"
export ZETA_CA_CSR="\${ZETA_CA}/csr"

export CLUSTER_ZETACA_LOCKED="1"
EOF

. $CLUSTER_ZETACA_CONF


@go.log INFO "Zeta CA Conf created at $CLUSTER_ZETACA_CONF"




