#!/bin/bash
#
# cluster zetaca install
#
# Run through creation scripts, create new CA and run
#
# Arguments:  (Optional) -u to not ask questions and just go
#
sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$MAPR_CONF"
sourceconf "$CLUSTER_CONF"
initconf "$CLUSTER_ZETACA_CONF"

function _zetaca_install() {
    UNATTEND="0"
    if [ "$1" == "-u" ]; then
        UNATTEND="1"
    fi


    if [ -f "$ZETACA_HOME/CA/cacert.pem" ]; then
        @go.log FATAL "A cacert.pem file already exists in ${ZETACA_HOME}/CA will not install certs"
    fi

    ./zeta cluster zetaca build
    ./zeta cluster zetaca cascripts
    ./zeta cluster zetaca certcreation
    @go.log INFO "Zeta CA App Submitted to Marathon: Waiting for deployment to finish before moving on"

    ./zeta cluster marathon submit "$ZETACA_HOME/marathon.json" "$MARATHON_SUBMIT" 1


    sleep 5
    echo ""
    echo "It's highly recommended you update nodes with the Zeta CA Master certificate"
    echo "You can do that for each node by running:"
    echo ""
    echo "./zeta cluster zetaca updatenode %NODENAME%"
    echo ""
    if [ "$UNATTEND" == "1" ]; then
        UPDATENODES="Y"
    else
        read -e -p "Do you wish to update all nodes now? " -i "Y" UPDATENODES
    fi
    echo ""
    if [ "$UPDATENODES" == "Y" ]; then
        @go.log INFO "Updating CA Certs on all nodes"
        ./zeta cluster zetaca updatenode -a -u
    else
        @go.log INFO "Not updating Certificates on nodes"
    fi

}



_zetaca_install "$@"

