#!/bin/bash
#
# Create the user prep script if it doesn't exist
#

# Create the script that will be executed on each machine to add the users

SCRIPTSRC="./conf/userupdate.sh"
sourceconf "$PREP_CONF"
if [ -f "$SCRIPTSRC" ]; then
    echo "User update script already exists at $SCRIPTSRC"
    echo "Should we replace?"
    read -e -p "Replace? " -i "N" REPLACE
    if [ "$REPLACE" == "Y" ]; then
        rm $SCRIPTSRC
    else
        @go.log FATAL "User update script already exists, not updating"
    fi
fi

touch $SCRIPTSRC
chmod 700 $SCRIPTSRC


if [ "$PRIV_CMD" == "sudo" ]; then
    ADDSUDO="sudo sed -i \"s/Defaults    requiretty//g\" /etc/sudoers"$'\n'
    ADDSUDO="${ADDSUDO}sudo sed -i \"s/Defaults   \\!visiblepw//g\" /etc/sudoers"$'\n'
else
    ADDSUDO="echo \"PRIV_CMD is not sudo - not adding to sudoers\""
fi



cat > $SCRIPTSRC << EOF
#!/bin/bash

$ADDSUDO

FSUSERPASS="$FSUSER_PASS"
IUSERPASS="$IUSER_PASS"


DIST_CHK=\$(egrep -i -ho 'ubuntu|redhat|centos' /etc/*-release | awk '{print toupper(\$0)}' | sort -u)
UB_CHK=\$(echo \$DIST_CHK|grep UBUNTU)
RH_CHK=\$(echo \$DIST_CHK|grep REDHAT)
CO_CHK=\$(echo \$DIST_CHK|grep CENTOS)

if [ "\$UB_CHK" != "" ]; then
    INST_TYPE="ubuntu"
    echo "Ubuntu"
elif [ "\$RH_CHK" != "" ] || [ "\$CO_CHK" != "" ]; then
    INST_TYPE="rh_centos"
    echo "Redhat"
else
    echo "Unknown lsb_release -a version at this time only ubuntu, centos, and redhat is supported"
    echo \$DIST_CHK
    exit 1
fi

echo "\$INST_TYPE"

if [ "\$INST_TYPE" == "ubuntu" ]; then
   adduser --disabled-login --gecos '' --uid=$IUSER_UID ${IUSER}
   adduser --disabled-login --gecos '' --uid=$FSUSER_UID ${FSUSER}
   echo "${IUSER}:\$IUSERPASS"|chpasswd
   echo "${FSUSER}:\$FSUSERPASS"|chpasswd
elif [ "\$INST_TYPE" == "rh_centos" ]; then
   adduser --uid $IUSER_UID ${IUSER}
   adduser --uid $FSUSER_UID ${FSUSER}
   echo "\$IUSERPASS"|passwd --stdin ${IUSER}
   echo "\$FSUSERPASS"|passwd --stdin ${FSUSER}
else
    echo "Relase not found, not sure why we are here, exiting"
    exit 1
fi
Z=\$(sudo grep ${IUSER} /etc/sudoers)
M=\$(sudo grep ${FSUSER} /etc/sudoers)

if [ "\$Z" == "" ] && [ "$PRIV_CMD" == "sudo" ]; then
    echo "Adding ${IUSER} to sudoers"
    echo "${IUSER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
fi
if [ "\$M" == "" ] && [ "$PRIV_CMD" == "sudo" ]; then
    echo "Adding $FSUSER to sudoers"
    echo "$FSUSER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
fi
EOF

@go.log INFO "User update script created at $SCRIPTSRC"
