#!/bin/bash
#
# This script walks the user through a series of questions in order to create a prep_conf.conf
#
. "$_GO_USE_MODULES" 'getpass'


echo ""
echo "-----------------------------------"
echo "This process will ask a series of questions in order to create a prep_conf.conf script for gettings nodes ready for Zeta"
echo "The configuration will be located: $PREP_CONF"
echo "-----------------------------------"
echo ""
echo "Initial User for Connection to Zeta Cluster"
echo "We need access to the initial nodes on the Zeta cluster. We do this through a username that has passwordless sudo and a key without a password"
echo "Once the zeta cluster is created, this user can be deprivileged."
echo ""
echo "We do try to detect this, through a list of users, you can provide a space separated list of users, or take ours as default"
echo ""
echo "For example, if this was AWS, and we were using ubuntu based nodes, I'd answer 'ubuntu' for the Initial users"
echo "If I were using ubuntu and centos I'd provide 'ubuntu centos' for the Intial users"
echo ""
read -e -p "Initial user list to connect to zeta nodes: " -i "ubuntu centos ec2-user" INIT_USERS
echo ""
echo "We now need the key for the initial connection, this is typically location in /home/$INIT_USER/.ssh/id_rsa, but doesn't have to be. Please specify that here"
echo ""
read -e -p "Private key for initial user on zeta nodes: " -i "/home/$INIT_USER/.ssh/id_rsa" INIT_KEY_LOC
echo ""
GEN_KEY="Y"
OUT_KEY="./conf/iuser.key"
OUT_KEY_PUB="./conf/iuser.key.pub"
echo ""
echo "As part of this process, we will generate a key for the IUSER user"
echo "It will be stored at $OUT_KEY and its public key will be stored at $OUT_KEY_PUB"
echo "These values will be saved in the conf for use as well"
echo ""
ZETAADM_UID="2500"
MAPR_UID="2000"

IUSER="zetaadm" # The Main User for Zeta
echo "-----------------------------------"
echo "The UID for the IUSER user will be $ZETAADM_UID and the UID for the mapr user will be $MAPR_UID"
echo "These values are stored in the conf"
echo ""
echo "-----------------------------------"
echo ""
getpass "$IUSER" ZETAADM_PASS
echo ""
getpass "mapr" MAPR_PASS
echo ""
echo "-----------------------------------"
echo "Please enter the list of nodes we will be preparing for Zeta, the nodes should be space separated"
echo ""
read -e -p "Enter list of space separated nodes for use in Zeta: " NODES
echo ""
echo "In setting up Zeta, we like to select an 'Initial' node that can be used as the node that all the scripts run from. It should be an agent node"
echo ""
read -e -p "Enter initial node for Zeta install: " INIT_NODE
echo ""
echo ""
echo "-----------------------------------"
echo "As we are prepping the nodes, it's helpful to have a list of interfaces to check for the internal IP Address of the nodes. "
echo "Basically provide a space separated list, and the first interface in that list that returns an IP will be the lucky winner"
echo ""
read -e -p "Interface to check list: " -i "eth0 em1 eno1 enp2s0 enp3s0 ens192" INTERFACE_LIST

touch $PREP_CONF
chmod 640 $PREP_CONF

cat > $PREP_CONF << EOF
#!/bin/bash
#
# Configuration script for prepping nodes for Zeta Architecture

# INIT_USER is the user to connect to the cluster in order to establish the initial users, and installs for Zeta
INIT_USERS="$INIT_USERS"
# INIT_KEY_LOC is the location of the SSH private key to connect to the cluster with
INIT_KEY_LOC="$INIT_KEY_LOC"

# The Main user for Zeta  (zetaadm by default)
IUSER="$IUSER"

# The following Variables determine whether to generate a key for zetaadm, what that key will be called, and what the public key will be called
GEN_KEY="$GEN_KEY"
OUT_KEY="$OUT_KEY"
OUT_KEY_PUB="$OUT_KEY_PUB"

# The UIDs for zetaadm and mapr
ZETAADM_UID="$ZETAADM_UID"
MAPR_UID="$MAPR_UID"

# Passwords for mapr and zetaadm
MAPR_PASS="$MAPR_PASS"
ZETAADM_PASS="$ZETAADM_PASS"

# Node list to prep
NODES="$NODES"

# Initial Node to use for staging
INIT_NODE="$INIT_NODE"

# Interfaces to check for internal IPs (in order)
INTERFACE_LIST="$INTERFACE_LIST"

# If this is set to 1, scripts will assume "Use" when the conf exists. 
PREP_LOCKED="0"

EOF

@go.log INFO "Prep Conf file written to $PREP_CONF"

