#!/bin/bash
#
# Create the user prep script if it doesn't exist
#

# Create the script that will be executed on each machine to add the users

SCRIPTSRC="./conf/userupdate.sh"
. $PREP_CONF
if [ -f "$SCRIPTSRC" ]; then
    echo "User update script already exists at $SCRIPTSRC"
    echo "Should we replace?"
    read -e -p "Replace? " -i "N" REPLACE
    if [ "$REPLACE" == "Y" ]; then
        rm $SCRIPTSRC
    else
        @go.log FATAL "User update script already exists, not updating"
    fi
fi

touch $SCRIPTSRC
chmod 700 $SCRIPTSRC

cat > $SCRIPTSRC << EOF
#!/bin/bash

sudo sed -i "s/Defaults    requiretty//g" /etc/sudoers
sudo sed -i "s/Defaults   \!visiblepw//g" /etc/sudoers

MAPRPASS="$MAPR_PASS"
ZETAPASS="$ZETAADM_PASS"


DIST_CHK=\$(egrep -i -ho 'ubuntu|redhat|centos' /etc/*-release | awk '{print toupper(\$0)}' | sort -u)
UB_CHK=\$(echo \$DIST_CHK|grep UBUNTU)
RH_CHK=\$(echo \$DIST_CHK|grep REDHAT)
CO_CHK=\$(echo \$DIST_CHK|grep CENTOS)

if [ "\$UB_CHK" != "" ]; then
    INST_TYPE="ubuntu"
    echo "Ubuntu"
elif [ "\$RH_CHK" != "" ] || [ "\$CO_CHK" != "" ]; then
    INST_TYPE="rh_centos"
    echo "Redhat"
else
    echo "Unknown lsb_release -a version at this time only ubuntu, centos, and redhat is supported"
    echo \$DIST_CHK
    exit 1
fi

echo "\$INST_TYPE"

if [ "\$INST_TYPE" == "ubuntu" ]; then
   adduser --disabled-login --gecos '' --uid=$ZETAADM_UID zetaadm
   adduser --disabled-login --gecos '' --uid=$MAPR_UID mapr
   echo "zetaadm:\$ZETAPASS"|chpasswd
   echo "mapr:\$MAPRPASS"|chpasswd
elif [ "\$INST_TYPE" == "rh_centos" ]; then
   adduser --uid $ZETAADM_UID zetaadm
   adduser --uid $MAPR_UID mapr
   echo "\$ZETAPASS"|passwd --stdin zetaadm
   echo "\$MAPRPASS"|passwd --stdin mapr
else
    echo "Relase not found, not sure why we are here, exiting"
    exit 1
fi
Z=\$(sudo grep zetaadm /etc/sudoers)
M=\$(sudo grep mapr /etc/sudoers)

if [ "\$Z" == "" ]; then
    echo "Adding zetaadm to sudoers"
    echo "zetaadm ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
fi
if [ "\$M" == "" ]; then
    echo "Adding mapr to sudoers"
    echo "mapr ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
fi
EOF

@go.log INFO "User update script created at $SCRIPTSRC"
