#!/bin/bash
#
# Determines prep status of a given node or all nodes via -a
#
# Arguments:
# -n="%NODE% Get status of a specific node
# -a Get status of all nodes in prep.conf
#

sourceconf "$PREP_CONF"

function _prep_status() {

    ALL="0"

    for i in "$@"
        do
        case $i in
            -a)
            ALL="1"
            ;;
            "-n="*)
            HOST="${i#*=}"
            ;;
            *)
            # unknown option
            ;;
        esac
    done


    if [ "$ALL" == "1" ]; then
        MYHOSTS="$NODES"
    else
        MYHOSTS="$HOST"
    fi

    if [ "$MYHOSTS" == "" ]; then
        @go.log FATAL "Must provide a host to connect and update status on via -n= or specify -a for all nodes"
    fi

    PREP_SCRIPT="./bin/prepstatus.sh"
    REM_LOC="/home/$IUSER/prepstatus.sh"
#printf "%-30s %-30s %-30s\n" "$PKG" "$PKGBASE" "$INST"

    if [ ! -f "$PREP_SCRIPT" ]; then
cat > $PREP_SCRIPT << EOF
#!/bin/bash
KERNEL=\$(uname -a|cut -d" " -f3)
UP="true"
SUDO_CHK=\$(sudo whoami)
SYS_TYPE=\$(/home/${IUSER}/system_type.sh)
DCK_VERS=\$(sudo docker info 2> /dev/null|grep "Server Version")

printf "%-30s %-30s %-30s %-30s %-30s\n" "\$UP" "\$SUDO_CHK" "\$KERNEL" "\$SYS_TYPE" "\$DCK_VERS"

EOF
    chmod +x $PREP_SCRIPT
    fi



    printf "%-30s %-30s %-30s %-30s %-30s\n" "Host Up" "Sudo Check" "Kernel" "System Type" "Docker Version"
    echo "----------------------------------------------------------------------------------------------------------------------------------------------------------"
    for HOST in $MYHOSTS; do

        scp -q -i ${OUT_KEY} $PREP_SCRIPT ${IUSER}@${HOST}:$REM_LOC
        if [ "$?" == "0" ]; then
            ssh -i ${OUT_KEY} ${IUSER}@${HOST} $REM_LOC
        else
            printf "%-30s %-30s %-30s %-30s %-30s\n" "false" "-" "-" "-" "-"
        fi
    done
}

_prep_status "$@"
