#!/bin/bash
#
# Update system packages on Zeta nodes for initial install
#
# Arguments
# -n=%HOSTNAME% - The host to run the system prep on
# -u - Run attended (don't wait to complete)
#

sourceconf "$PREP_CONF"

function _displayhelp(){
    echo "prep systemprep - Update system packages on Zeta nodes"
    echo "===================================================================================================="
    echo ""
    echo "Arguments:"
    echo "-u               - Unattended install"
    echo "-h               - Display this help"
    echo "-n=%NODE%        - Run on the node %NODE%"
    echo ""
    echo "Usage:"
    echo "./zeta prep systemprep -n=\"192.168.0.1\" # Run the systemprep on node 192.168.0.1"
    echo ""
}


function _systemprep() {

    UNATTEND="0"
    DISPLAYHELP="0"
    for i in "$@"
        do
        case $i in
            -u)
            UNATTEND="1"
            ;;
            -h)
            DISPLAYHELP="1"
            ;;
            "-n="*)
            HOST="${i#*=}"
            ;;
            *)
            # unknown option
            ;;
        esac
    done
    if [ "$DISPLAYHELP" == "1" ]; then
        _displayhelp
        exit 0
    fi
    SCRIPTS="./bin/ubuntu_prep.sh ./bin/centos_prep1.sh ./bin/centos_prep2.sh"

    FOUND="1"
    for SCRIPT in $SCRIPTS; do
        if [ ! -f "$SCRIPT" ]; then
            FOUND="0"
        fi
    done
    if [ "$FOUND" == "0" ]; then
        @go.log INFO "System Scripts not found, creating in ./bin"
        if [ "$UNATTEND" == "1" ]; then
            ./zeta prep createsystemprep -u
        else
            ./zeta prep createsystemprep
        fi

    fi
    if [ ! -f "$OUT_KEY" ]; then
        @go.log INFO "Prep conf exists, however, keys have not been generated, doing so now"
        ./zeta prep genkey
    fi

    if [ "$HOST" == "" ]; then
        @go.log FATAL "Must provide a host to connect and update using -n="
    fi

    @go.log INFO "Connecing to and updating host $HOST"

    scp -o StrictHostKeyChecking=no -i ${OUT_KEY} ./bin/system_type.sh ${IUSER}@${HOST}:/home/${IUSER}/system_type.sh
    SYS_TYPE=$(ssh -i ${OUT_KEY} ${IUSER}@${HOST} "/home/${IUSER}/system_type.sh")
    ssh -i ${OUT_KEY} ${IUSER}@${HOST} "$PRIV_CMD mkdir -p /root/scripts && $PRIV_CMD chown root:root /root/scripts && $PRIV_CMD chmod 700 /root/scripts"
    @go.log INFO "System Type: $SYS_TYPE - Running Appropriate Scripts"
    if [ "$SYS_TYPE" == "ubuntu" ]; then
        scp -i ${OUT_KEY} ./bin/ubuntu_prep.sh ${IUSER}@${HOST}:/home/${IUSER}/ubuntu_prep.sh
        if [ "$UNATTEND" == "1" ]; then
            ssh -i ${OUT_KEY} ${IUSER}@${HOST} "$PRIV_CMD sh -c 'mv /home/${IUSER}/ubuntu_prep.sh /root/scripts/; nohup /root/scripts/ubuntu_prep.sh > /dev/null 2>&1 &'"
        else
            ssh -i ${OUT_KEY} ${IUSER}@${HOST} "$PRIV_CMD mv /home/${IUSER}/ubuntu_prep.sh /root/scripts/ && $PRIV_CMD /root/scripts/ubuntu_prep.sh"
        fi
    elif [ "$SYS_TYPE" == "rh_centos" ]; then
        scp -i ${OUT_KEY} ./bin/centos_prep1.sh ${IUSER}@${HOST}:/home/${IUSER}/centos_prep1.sh
        scp -i ${OUT_KEY} ./bin/centos_prep2.sh ${IUSER}@${HOST}:/home/${IUSER}/centos_prep2.sh
        if [ "$UNATTEND" == "1" ]; then
            ssh -i ${OUT_KEY} ${IUSER}@${HOST} "$PRIV_CMD sh -c 'mv /home/${IUSER}/centos_prep1.sh /root/scripts/; mv /home/${IUSER}/centos_prep2.sh /root/scripts/; nohup /root/scripts/centos_prep1.sh > /dev/null 2>&1 &'"
        else
            ssh -i ${OUT_KEY} ${IUSER}@${HOST} "$PRIV_CMD mv /home/${IUSER}/centos_prep1.sh /root/scripts/ && $PRIV_CMD mv /home/${IUSER}/centos_prep2.sh /root/scripts/ && $PRIV_CMD /root/scripts/centos_prep1.sh"
        fi
    else
        @go.log ERROR "Unknown System Type: $SYS_TYPE"
    fi
}

_systemprep "$@"
