#!/bin/bash
#
# Show Status of Nodes in Zeta ENV
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$NODE_CONF"

reqshared "dockerregv2 zetaca openldap"


function _nodestatus() {

    MASTERS="0"
    AGENTS="0"
    ALL="0"
    HOST=""
    MYHOSTS=""

    for i in "$@"
        do
        case $i in
            "-m")
            MASTERS="1"
            ;;
            "-a")
            AGENTS="1"
            ;;
            "-n="*)
            HOST="${i#*=}"
            ;;
            *)
            # unknown option
            ;;
        esac
    done


    if [ "$HOST" == "" ]; then
        if [ "$MASTERS" == "0" ] && [ "$AGENTS" == "0" ]; then
            @go.log INFO "No host provided (with -n) and -a or -m not specified, assuming all nodes"
            ALL=1
        elif [ "$MASTERS" == "1" ] && [ "$AGENTS" == "1" ]; then
            ALL=1
        fi
    else
        @go.log INFO "Host provided with -n= - Ignoring other flags"
    fi

    if [ "$ALL" == "1" ]; then
        MYHOSTS="$INTERNAL_NODES"
    else
        if [ "$HOST" != "" ]; then
            MYHOSTS="$HOST"
        else
            if [ "$MASTERS" == "1" ]; then
                MYHOSTS="$MASTER_NODES"
            fi
            if [ "$AGENTS" == "1" ]; then
                MYHOSTS="$AGENT_NODES"
            fi
        fi
    fi

    echo "Hosts to Check Status on: $MYHOSTS"

cat > ./bin/node_status.sh << EOF
#!/bin/bash
CLUSTERNAME="$CLUSTERNAME"
CLUSTERROOT="$CLUSTERROOT"
IUSER="$IUSER"

MNT=\$(ls /$CLUSTERROOT|grep $CLUSTERNAME)
if [ "\$MNT" != "" ]; then
    FUSE_MOUNTED="true"
else
    FUSE_MOUNTED="false"
fi


HNAME=\$(hostname)
KERNEL=\$(uname -a|cut -d" " -f3)
UP="true"
MESOS_ROLE=\$(sudo systemctl list-units|grep -P -o "dcos-mesos-[^\.]+\.service"|sed "s/dcos-mesos-//g"|sed "s/\.service//g")
SYS_TYPE=\$(/home/${IUSER}/system_type.sh)
DCK_VERS=\$(sudo docker info 2> /dev/null|grep "Server Version")

printf "%-30s %-30s %-30s %-30s %-30s %-30s %-30s\n" "$HNAME" "$UP"  "$KERNEL" "$SYS_TYPE" "$DCK_VERS" "$MESOS_ROLE"  "$FUSE_MOUNTED"

EOF
    chmod +x ./bin/node_status.sh
    DASHES="------------------------------"
    printf "%-30s %-30s %-30s %-30s %-30s %-30s %-30s\n" "Hostname" "Host Up" "Kernel" "System Type" "Docker Version" "Mesos SVC Role" "Fuse Mounted"
    printf "%-30s %-30s %-30s %-30s %-30s %-30s %-30s\n" "$DASHES" "$DASHES" "$DASHES" "$DASHES" "$DASHES" "$DASHES" "$DASHES"
    for 




}

_nodestatus "$@"
