#!/bin/bash
#
# marathon delete
# This takes two arguments
# - Marathon ID
# - MARATHON Submit URL
# - Optional Wait for Deployment to finish - Put 1 if you want to wait
#
# Example: ./zeta cluster marathon delete myrole/myapp http://marathon.mesos:8080/v2/apps
function _marathon_delete() {


    MARID=$1
    MARATHON_URL=$2
    WAIT=$3

    MARATHON_DEP="http://$MARATHON_HOST/v2/deployments"

    OUT=$(curl -s -X DELETE ${MARATHON_URL}/${MARID} -H "Content-type: application/json")

    DEP_ID=$(echo $OUT|grep -P -o "deploymentId\":\"[^\"]+\""|cut -f2 -d":"|sed "s/\"//g")

    if [ "$WAIT" == "1" ]; then
        @go.log INFO "Waiting for app destroy request on ID $MARID to finish deployment with ID $DEP_ID"

        DEPLOY=$(curl -s -H "Content-type: application/json" -X GET ${MARATHON_DEP}|grep "$DEP_ID")
        while [ "$DEPLOY" != "" ]; do
            @go.log INFO "Waiting in a loop for Deployment: $DEP_ID to finish"
            sleep 2
            DEPLOY=$(curl -s -H "Content-type: application/json" -X GET ${MARATHON_DEP}|grep "$DEP_ID")
        done
        echo ""
        @go.log INFO "Destroy application Deployement with ID $DEP_ID complete"
    else
        @go.log INFO "Destroy application $MARID request submitted - Not waiting to finish deployment"
    fi

}

_marathon_delete "$@"







