#!/bin/bash
#
# Interface to do user things in Zeta
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$MAPR_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"

AUTH_LIB="lib${LDAP_PROVIDER}"

# Load the Auth lib for this cluster
. "$_GO_USE_MODULES" $AUTH_LIB
. "$_GO_USE_MODULES" 'getpass'
. "$_GO_USE_MODULES" 'libmapr'
function _user() {

    . /mapr/$CLUSTERNAME/zeta/kstore/env/zeta_shared.sh

    ACTION_SRC="user"
    for i in "$@"
        do
        case $i in
            -a)
            ACTION_ADD="1"
            ;;
            -d)
            ACTION_DEL="1"
            ;;
            -q)
            ACTION_QUERY="1"
            ;;
            -p)
            ACTION_RESETPASS="1"
            ;;
            -u)
            UNATTEND="1"
            ;;
            "-n="*)
            USER_NAME="${i#*=}"
            ;;
            "-i="*)
            USER_UID="${i#*=}"
            ;;
            "-f="*)
            USER_FNAME="${i#*=}"
            ;;
            "-l="*)
            USER_LNAME="${i#*=}"
            ;;
            "-r="*)
            USER_ROLE="${i#*=}"
            ;;
            *)
            # unknown option
            ;;
        esac
    done


    if [ "$ACTION_ADD" == "1" ]; then
        if [ "$ACTION_DEL" == "1" ] || [ "$ACTION_QUERY" == "1" ] || [ "$ACTION_RESETPASS" == "1" ]; then
            @go.log FATAL "Requested $ACTION_SRC Add (-a) specified with either $ACTION_SRC Delete (-d),  $ACTION_SRC Query (-q), or $ACTION_SRC Reset Password  (-p) - Exiting"
        fi
        if [ "$USER_NAME" == "" ]; then
            @go.log FATAL "To add a user you must provide a user name with -n"
        fi
        if [ "$USER_UID" == "" ]; then
            @go.log FATAL "To add a useryou must provide a user id with -i"
        fi
        if [ "$USER_ROLE" == "" ]; then
            @go.log WARN "No User Role Provided: Defaults to shared role"
            USER_ROLE="shared"
        fi
        if [ "$USER_ROLE" != "" ]; then
            START_UID=$(cat /mapr/$CLUSTERNAME/zeta/kstore/zetasync/zetauid.list|grep $USER_ROLE|cut -d":" -f2)

            if [ "$START_UID" == "" ]; then
                @go.log FATAL "The starting UID for role $USER_ROLE was not found, are you sure this role is installed?"
            fi
            VALID_UID="$START_UID"
        fi
        if [ "$USER_UID" -ge $VALID_UID ] && [ "$USER_UID" -lt $(($VALID_UID + 500000)) ]; then
            echo "$USER_UID is valid in role $USER_ROLE - However we do not check for duplicates (yet)"
        else
            @go.log FATAL "$USER_UID is not valid in role $USER_ROLE"
        fi

        if [ "$USER_FNAME" == "" ]; then
            echo "Please enter the user's first name: "
            read -e -p "Firstname: " USER_FNAME
        fi
        if [ "$USER_LNAME" == "" ]; then
            echo "Please enter the user's last name: "
            read -e -p "Lastname: " USER_LNAME
        fi


    elif [ "$ACTION_DEL" == "1" ]; then
        if [ "$ACTION_ADD" == "1" ] || [ "$ACTION_QUERY" == "1" ] || [ "$ACTION_RESETPASS" == "1" ]; then
            @go.log FATAL "Requested $ACTION_SRC Delete (-d) specified with either $ACTION_SRC Add (-a), $ACTION_SRC Query (-q), or $ACTION_SRC Reset Password  (-p) - Exiting"
        fi
    elif [ "$ACTION_QUERY" == "1" ]; then
        if [ "$ACTION_ADD" == "1" ] || [ "$ACTION_DEL" == "1" ] || [ "$ACTION_RESETPASS" == "1" ]; then
            @go.log FATAL "Requested $ACTION_SRC Query (-q) specified with either $ACTION_SRC Add (-a) , $ACTION_SRC Delete (-d), or $ACTION_SRC Reset Password  (-p) - Exiting"
        fi
    elif [ "$ACTION_RESETPASS" == "1" ]; then
        if [ "$ACTION_ADD" == "1" ] || [ "$ACTION_DEL" == "1" ] || [ "$ACTION_QUERY" == "1" ]; then
            @go.log FATAL "Requested $ACTION_SRC Reset Password (-p) specified with either $ACTION_SRC Add (-a) , $ACTION_SRC Delete (-d), or $ACTION_SRC Query (-q) - Exiting"
        fi
    else
        @go.log FATAL "./zeta users user invoked without specifying either Add, Delete, Query, or Reset Password - Exiting"
    fi

    if [ "$ACTION_ADD" == "1" ]; then
        getpass "$USER_NAME" USER_PASS
        hashpass "$USER_PASS" USER_HASH

        echo "You wish to create the following user:"
        echo ""
        echo "User: $USER_NAME"
        echo "UID: $USER_UID"
        echo "Role: $USER_ROLE"
        echo "First Name: $USER_FNAME"
        echo "Last Name: $USER_LNAME"
        echo ""
        if [ "$UNATTEND" != "1" ]; then
            read -e -p "Is this correct? " -i "N" CHK
            if [ "$CHK" != "Y" ]; then
                @go.log FATAL "User did not confirm user creation"
            fi
        fi
        @go.log INFO "Adding User: $USER_NAME with UID $USER_UID to role $USER_ROLE"
        adduser "$USER_NAME" "$USER_UID" "$USER_FNAME" "$USER_LNAME" "$USER_ROLE" "$USER_HASH"

        @go.log INFO "User $USER_NAME Added to LDAP - Waiting for ldap sync"
        sleep 1
        TST=$(id $USER_NAME)
        while [ "$TST" == "" ]; do
            echo "...waiting for ldap sync"
            sleep 1
            TST=$(id $USER_NAME)
        done

        if [ ! -d "/mapr/$CLUSTERNAME/user/$USER_NAME" ]; then
            @go.log INFO "$USER_NAME Home Directory not found: Creating"
            maprapi "/volume/create?name=user.${USER_NAME}&path=/user/${USER_NAME}&rootdirperms=770&user=${USER_NAME}:fc,a,dump,restore,m,d%20${IUSER}:fc,a,dump,restore,m,d%20mapr:fc,a,dump,restore,m,d&ae=${USER_NAME}" "10"
            echo ""
            T=""
            while [ "$T" == "" ]; do
                sleep 1
                T=$(ls -1 /mapr/$CLUSTERNAME/user|grep $USER_NAME)
            done
            sudo chown $USER_NAME:$IUSER /mapr/$CLUSTERNAME/user/$USER_NAME
            sudo chmod 770 /mapr/$CLUSTERNAME/user/$USER_NAME
        else
            @go.log WARN "User Directory for $USER_NAME Already Exists: Ensure to check permissions for reuse"
        fi


    elif [ "$ACTION_DEL" == "1" ]; then
        @go.log FATAL "$ACTION_SRC Deletion not yet implemented"
    elif [ "$ACTION_QUERY" == "1" ]; then
        @go.log FATAL "$ACTION_SRC Query not yet implemented"
    elif [ "$ACTION_RESETPASS" == "1" ]; then
        @go.log FATAL "$ACTION_SRC Reset Password not yet implemented"
    else
        @go.log FATAL "Unknown Command requested"
    fi

}
_user "$@"
