#!/bin/bash
#
# Interface to do user things in Zeta
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"


# Load the Auth lib for this cluster
AUTH_LIB="lib${LDAP_PROVIDER}"
. "$_GO_USE_MODULES" $AUTH_LIB

# Load the FS lib for this cluster
FS_LIB="lib${FS_PROVIDER}"
. "$_GO_USE_MODULES" $FS_LIB


function _print_user_help() {

    echo "##########################"
    echo ""
    echo "Zeta user Options"
    echo "--------------------------"
    echo "./zeta users user"
    echo " -a  # Add user"
    echo " -d  # Delete user (not yet implemented)"
    echo " -q  # Query user (not yet implemented)"
    echo " -p  # Reset password"
    echo ""
    echo "_______________"
    echo "Add user Required Options (-a)"
    echo " -n=\"username2add\"     # Username to add"
    echo ""
    echo "Add user Optional Options (-a)"
    echo " -r=\"roletoadd\"        # Defaults to shared role"
    echo " -i=\"User UID\"         # Defaults to next available in role"
    echo " -f=\"User First Name\"  # Prompts if not provided"
    echo " -l=\"User Last Name\"   # Prompts if not provided"
    echo " -u                      # Unattended - Only works if all information provided"
    echo " -ad=\"user@domain.com\" # Sets proxy password linked account instead of setting password (ensure proxy passthrough is working) (Defaults to prompting for password)"
    echo ""
    echo "_______________"
    echo "Reset Password Required Options (-p)"
    echo " -n=\"username\"         # username to reset password for"
    echo ""
    echo "Reset Psasword Optional Options (-p)"
    echo " -r=\"role\"             # Role that username is in (defaults to trying shared)"
    echo " -ad=\"user@domain.com\" # Sets password to proxy link to specified account (ensure proxy passthrough is working) (Defaults to prompting for password)"
    echo " -u                      # Unattended - Only works if setting to proxy passthrough, otherwise will prompt for password"
    echo ""

}

function _user() {

    . $CLUSTERMOUNT/zeta/kstore/env/zeta_shared.sh
    PASS_LINK=""
    ACTION_SRC="user"
    for i in "$@"
        do
        case $i in
            -a)
            ACTION_ADD="1"
            ;;
            -d)
            ACTION_DEL="1"
            ;;
            -q)
            ACTION_QUERY="1"
            ;;
            -p)
            ACTION_RESETPASS="1"
            ;;
            -u)
            UNATTEND="1"
            ;;
            "-n="*)
            USER_NAME="${i#*=}"
            ;;
            "-ad="*)
            PASS_LINK="${i#*=}"
            ;;
            "-i="*)
            USER_UID="${i#*=}"
            ;;
            "-f="*)
            USER_FNAME="${i#*=}"
            ;;
            "-l="*)
            USER_LNAME="${i#*=}"
            ;;
            "-r="*)
            USER_ROLE="${i#*=}"
            ;;
            *)
            # unknown option
            ;;
        esac
    done


    if [ "$ACTION_ADD" == "1" ]; then
        if [ "$ACTION_DEL" == "1" ] || [ "$ACTION_QUERY" == "1" ] || [ "$ACTION_RESETPASS" == "1" ]; then
            _print_user_help
            @go.log FATAL "Requested $ACTION_SRC Add (-a) specified with either $ACTION_SRC Delete (-d),  $ACTION_SRC Query (-q), or $ACTION_SRC Reset Password  (-p) - Exiting"
        fi
        if [ "$USER_NAME" == "" ]; then
            _print_user_help
            @go.log FATAL "To add a user you must provide a user name with -n"
        fi
        if [ "$USER_ROLE" == "" ]; then
            @go.log WARN "No User Role Provided: Defaults to shared role"
            USER_ROLE="shared"
        fi
        if [ "$USER_ROLE" != "" ]; then
            UIDLOC="./conf/zetasync/zetauid.list"
            OLDLOC="$CLUSTERMOUNT/zeta/kstore/zetasync/zetauid.list"
            if [ ! -f "$UIDLOC" ]; then
                if [ -f "$OLDLOC" ]; then
                    @go.log INFO "Copying old zetasync location to ./conf"
                    mkdir -p ./conf/zetasync
                    cp $OLDLOC $UIDLOC
                else
                     _print_user_help
                    @go.log FATAL "Cannot find zetauid.list in ./conf/zetasync or in /zeta/kstore/zetasync - Exiting"
                fi
            fi

            START_UID=$(cat $UIDLOC|grep $USER_ROLE|cut -d":" -f2)

            if [ "$START_UID" == "" ]; then
                 _print_user_help
                @go.log FATAL "The starting UID for role $USER_ROLE was not found, are you sure this role is installed?"
            fi
            VALID_UID="$START_UID"
        fi
        if [ "$USER_UID" == "" ]; then
            @go.log INFO "No UID specified, getting next available"
            retnextuid "USER_UID" "$USER_ROLE"
        else
            if [ "$USER_UID" -ge $VALID_UID ] && [ "$USER_UID" -lt $(($VALID_UID + 500000)) ]; then
                @go.log WARN "$USER_UID is valid in role $USER_ROLE - However we do not check for duplicates (yet)"
            else
                @go.log FATAL "$USER_UID is not valid in role $USER_ROLE"
            fi
        fi

        if [ "$USER_FNAME" == "" ]; then
            echo "Please enter the user's first name: "
            read -e -p "Firstname: " USER_FNAME
        fi
        if [ "$USER_LNAME" == "" ]; then
            echo "Please enter the user's last name: "
            read -e -p "Lastname: " USER_LNAME
        fi


    elif [ "$ACTION_DEL" == "1" ]; then
        if [ "$ACTION_ADD" == "1" ] || [ "$ACTION_QUERY" == "1" ] || [ "$ACTION_RESETPASS" == "1" ]; then
             _print_user_help
            @go.log FATAL "Requested $ACTION_SRC Delete (-d) specified with either $ACTION_SRC Add (-a), $ACTION_SRC Query (-q), or $ACTION_SRC Reset Password  (-p) - Exiting"
        fi
    elif [ "$ACTION_QUERY" == "1" ]; then
        if [ "$ACTION_ADD" == "1" ] || [ "$ACTION_DEL" == "1" ] || [ "$ACTION_RESETPASS" == "1" ]; then
             _print_user_help
            @go.log FATAL "Requested $ACTION_SRC Query (-q) specified with either $ACTION_SRC Add (-a) , $ACTION_SRC Delete (-d), or $ACTION_SRC Reset Password  (-p) - Exiting"
        fi
    elif [ "$ACTION_RESETPASS" == "1" ]; then
        if [ "$ACTION_ADD" == "1" ] || [ "$ACTION_DEL" == "1" ] || [ "$ACTION_QUERY" == "1" ]; then
             _print_user_help
            @go.log FATAL "Requested $ACTION_SRC Reset Password (-p) specified with either $ACTION_SRC Add (-a) , $ACTION_SRC Delete (-d), or $ACTION_SRC Query (-q) - Exiting"
        fi
    else
         _print_user_help
        @go.log FATAL "./zeta users user invoked without specifying either Add, Delete, Query, or Reset Password - Exiting"
    fi

    if [ "$ACTION_ADD" == "1" ]; then
        if [ "$PASS_LINK" == "" ]; then
            getpass "$USER_NAME" USER_PASS
            hashpass "$USER_PASS" USER_HASH
        else
            USER_HASH="{SASL}${PASS_LINK}"
        fi

        echo "You wish to create the following user:"
        echo ""
        echo "User: $USER_NAME"
        echo "UID: $USER_UID"
        echo "Role: $USER_ROLE"
        echo "First Name: $USER_FNAME"
        echo "Last Name: $USER_LNAME"
        if [ "$PASS_LINK" != "" ]; then
            echo "Password proxy linked account: $PASS_LINK"
        else
            echo "Password: ***************"
        fi
        echo ""
        if [ "$UNATTEND" != "1" ]; then
            read -e -p "Is this correct? " -i "N" CHK
            if [ "$CHK" != "Y" ]; then
                 _print_user_help
                @go.log FATAL "User did not confirm user creation"
            fi
        fi
        @go.log INFO "Adding User: $USER_NAME with UID $USER_UID to role $USER_ROLE"
        adduser "$USER_NAME" "$USER_UID" "$USER_FNAME" "$USER_LNAME" "$USER_ROLE" "$USER_HASH"

        @go.log INFO "User $USER_NAME Added to LDAP - Waiting for ldap sync"
        sleep 1
        TST=$(id $USER_NAME)
        while [ "$TST" == "" ]; do
            echo "...waiting for ldap sync"
            sleep 2
            TST=$(id $USER_NAME)
        done
        sleep 3
        if [ ! -d "$CLUSTERMOUNT/user/$USER_NAME" ]; then
            @go.log INFO "$USER_NAME Home Directory not found: Creating"

            fs_mkvol "RETCODE" "/user/${USER_NAME}" "user.${USER_NAME}" "770"
            $PRIV_CMD chown -R ${USER_NAME}:${IUSER} $CLUSTERMOUNT/user/${USER_NAME}
            $PRIV_CMD chmod 770 ${CLUSTERMOUNT}/user/$USER_NAME
        else
            @go.log WARN "User Directory for $USER_NAME Already Exists: Ensure to check permissions for reuse"
        fi


    elif [ "$ACTION_DEL" == "1" ]; then
         _print_user_help
        @go.log FATAL "$ACTION_SRC Deletion not yet implemented"
    elif [ "$ACTION_QUERY" == "1" ]; then
         _print_user_help
        @go.log FATAL "$ACTION_SRC Query not yet implemented"
    elif [ "$ACTION_RESETPASS" == "1" ]; then
        if [ "$USER_ROLE" == "" ]; then
            @go.log WARN "No User Role Provided: Defaults to shared role"
            USER_ROLE="shared"
        fi
        if [ "$PASS_LINK" == "" ]; then
            getpass "$USER_NAME" USER_PASS
            hashpass "$USER_PASS" USER_HASH
        else
            USER_HASH="{SASL}${PASS_LINK}"
        fi
        echo "You wish to change the password on the following user:"
        echo ""
        echo "User: $USER_NAME"
        echo "Role: $USER_ROLE"
        if [ "$PASS_LINK" != "" ]; then
            echo "Password proxy linked account: $PASS_LINK"
        else
            echo "Password: ***************"
        fi
        echo ""
        if [ "$UNATTEND" != "1" ]; then
            read -e -p "Is this correct? " -i "N" CHK
            if [ "$CHK" != "Y" ]; then
                 _print_user_help
                @go.log FATAL "User did not confirm password change"
            fi
        fi
        @go.log INFO "Changing Password on user $USER_NAME"
        setuserpass "$USER_ROLE" "$USER_NAME" "$USER_HASH"
    else
        _print_user_help
        @go.log FATAL "Unknown Command requested"
    fi

}
_user "$@"
