#!/bin/bash
#
# fs fsdocker - Install FS Docker Registry for Zeta
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"

ME=$(whoami)

if [ "$ME" != "${IUSER}" ]; then
    @go.log FATAL "This script must be run as ${IUSER}"
fi

REG_IP=$(./conf/ip-detect)

echo "You are running on the Docker registry on $REG_IP is this correct?"

read -e -p "Install on $REG_IP?  " -i "Y" INSTALL_HERE

if [ "$INSTALL_HERE" != "Y" ]; then
    @go.log FATAL "Not Installing"
fi

FSDOCKER_ROOT="/opt/fsdocker"

DOCKER_IMAGE_LOC="${FSDOCKER_ROOT}/images"

if [ -d "$DOCKER_IMAGE_LOC" ]; then
    @go.log FATAL "Docker image directory already exists at $DOCKER_IMAGE_LOC - Exiting"
fi

@go.log INFO "Creating Image Location"
sudo mkdir -p ${DOCKER_IMAGE_LOC}
APP_IMG="zeta/registry:2"

@go.log INFO "Pulling Docker Registry Image and renaming $APP_IMG"
sudo docker pull registry:2
sudo docker tag registry:2 $APP_IMG

@go.log INFO "Creating Certs for fsdocker"
APP_NAME="fsdocker"
APP_CERT_LOC="${FSDOCKER_ROOT}/dockercerts"

sudo mkdir -p ${APP_CERT_LOC}
sudo chown ${IUSER}:root ${APP_CERT_LOC}
sudo chmod 770 ${APP_CERT_LOC}
CN_GUESS="fsdocker-shared.marathon.slave.mesos"
. /home/${IUSER}/zetaca/zetaca_env.sh
. /home/${IUSER}/zetaca/gen_server_cert.sh



PORTSTR="CLUSTER:tcp:${FS_DOCKER_REG_PORT}:shared:fsdocker:FS Bootstrap Docker Registry"

getport "CHKADD" "Port for FS Bootstrap Docker Registry " "$SERVICES_CONF" "$PORTSTR" "1"

if [ "$CHKADD" != "" ]; then
    @go.log INFO "$FS_DOCKER_REG_PORT added to services port for the CLUSTER"
else
    @go.log FATAL "Adding Porting to services failed $PSTR"
fi


@go.log INFO "Creating Marathon file"
mkdir -p ./conf/marathon_files
MARATHON_FILE="./conf/marathon_files/fsdocker.marathon"
cat > ${MARATHON_FILE} << EOF
{
  "id": "shared/fsdocker",
  "cpus": 1,
  "mem": 1024,
  "instances": 1,
  "constraints": [["hostname", "LIKE", "$REG_IP"]],
  "labels": {
   "CONTAINERIZER":"Docker"
  },
  "env": {
    "REGISTRY_HTTP_TLS_CERTIFICATE": "/certs/srv_cert.pem",
    "REGISTRY_HTTP_TLS_KEY": "/certs/key-no-password.pem"
  },
  "ports": [],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "$APP_IMG",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 5000, "hostPort": ${FS_DOCKER_REG_PORT}, "servicePort": 0, "protocol": "tcp"}
      ]
    },
    "volumes": [
      { "containerPath": "/var/lib/registry", "hostPath": "${DOCKER_IMAGE_LOC}", "mode": "RW" },
      { "containerPath": "/certs", "hostPath": "${APP_CERT_LOC}", "mode": "RO" }
    ]
  }
}
EOF

@go.log INFO "Submitting FS Docker Reg to Marathon"

./zeta cluster marathon submit "$MARATHON_FILE" "$MARATHON_SUBMIT" 1


@go.log INFO "FS Docker Registry Running at fsdocker-shared.marathon.slave.mesos"
