#!/bin/bash
#
# mapr - Scripts to stage and run MapR on a DCOS cluster for Zeta
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
function _mapr() {

    LOCK="0"

    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    echo ""
    echo "********************************"
    echo "Scripts should now be run on cluster"
    echo "That should be: $INIT_NODE"
    echo "********************************"
    echo ""
    echo "Commands to use with fs mapr:"
    echo ""
    echo "./zeta fs mapr buildzk - Build the MapR ZK image"
    echo "./zeta fs mapr buildmapr - Build the MapR MapR image"
    echo "./zeta fs mapr installzk - Deploy and run the ZK image on all nodes per the mapr.conf file"
    echo "./zeta fs mapr installmapr - Deploy and run mapr docker images per the mapr.conf file"
    echo "./zeta fs mapr installfuse - Deplay fust client to all nodes in mapr.conf file"
    echo "./zeta fs mapr submitmaprnode  - Submit MapR Marathon JSON file for a single node"
    echo "./zeta fs mapr createlocalvols - Create local volumes for shuffle (-a for all nodes, -n=node, -s status)"
    echo "./zeta fs mapr fuseinstall - Install MapR FUSE Client on a single node"
    echo "./zeta fs mapr fuseremove - Remove MapR FUSE Client from a single node"
    echo "./zeta fs mapr installmaprnode - Install mapr to a single node"
    echo ""
    echo "./zeta fs mapr -l lock or unlock  mapr.conf file"
    echo ""


    if [ "$LOCK" == "1" ]; then
       lockconf "$FS_PROVIDER_CONF"
    fi

}

_mapr "$@"

