#!/bin/bash
#
# Build a package for use with Zeta
#
#
sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$MAPR_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"

reqshared "dockerregv2 zetaca openldap"

function _packagebuild() {

    UNATTEND="0"

  . /mapr/$CLUSTERNAME/zeta/kstore/env/zeta_shared.sh

    ACTION_SRC="user"
    for i in "$@"
        do
        case $i in
            -u)
            UNATTEND="1"
            ;;
            "-v="*)
            VERS_FILE="${i#*=}"
            ;;
            *)
            PKG_NAME="$i"
            # unknown option
            ;;
        esac
    done

    if [ "$PKG_NAME" == "" ]; then
        @go.log FATAL "You must specify a Package name"
    fi

    echo "Unattended: $UNATTEND"
    echo "Vers File: $VERS_FILE"
    echo "Package: $PKG_NAME"










}


_packagebuild "$@"
