#!/bin/bash
#
# Create conf file for  package management
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"

reqshared "dockerregv2 zetaca openldap"

# Main packages that ship with zetago
CORE_PKG_LOC="../zetapkgs"

# Core base install
SHARED_LOC="$CLUSTERMOUNT/zeta/shared"

# Additional Package Repo locations (This can be multiple directories separated by commas)
ADD_PKG_LOC="../zetaextra"

CUR=$(pwd)

read -e -p "Should we clone zetapkgs into the default location (../) (Y/N)" -i "Y" CLONEPKG
if [ "$CLONEPKG" == "Y" ]; then
    cd ..
    echo "Cloning zetapkgs into ../ "
    git clone https://github.com/johnomernik/zetapkgs
    cd $CUR
fi
read -e -p "Should we clone zetaextra into the default location (../) (Y/N)" -i "Y" CLONEEXTRA
if [ "$CLONEEXTRA" == "Y" ]; then
    cd ..
    echo "Cloning zetapextra into ../ "
    git clone https://github.com/johnomernik/zetaextra
    cd $CUR
fi

echo ""
echo "Core Package Location: $CORE_PKG_LOC"
echo ""
echo "Shared Install Location: $SHARED_LOC"
echo ""
echo "Additional PKG Roots (Comma separated) (Can be added later): $ADD_PKG_LOC"
echo ""

cat > $PACKAGE_CONF << EOP
#!/bin/bash

# The core location for Packages in your zeta Architecture
CORE_PKG_LOC="$CORE_PKG_LOC"

# The shared location typically CLUSTERMOUNT/zeta/shared
SHARED_LOC="$SHARED_LOC"

# Path to additional package locations separated by commas
ADD_PKG_LOC="$ADD_PKG_LOC"

PACKAGE_LOCKED="1"
EOP

@go.log INFO "Package Management conf created at $PACKAGE_CONF"

