#!/bin/bash
#
# Stop  an already installed package
#
# Arguments:
#
sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$PACKAGE_CONF"

reqshared "dockerregv2 zetaca openldap"

. "$_GO_USE_MODULES" 'libpackage'


function _packagestop() {

    MYDIR=$(pwd)

    UNATTEND="0"

  . $CLUSTERMOUNT/zeta/kstore/env/zeta_shared.sh

    ACTION_SRC="user"
    for i in "$@"
        do
        case $i in
            *)
            CONF_FILE="$i"
            # unknown option
            ;;
        esac
    done

    if [ ! -f "$CONF_FILE" ]; then
        @go.log FATAL "You must specify a path to a conf file"
    fi

    . $CONF_FILE

    # Determine the package base
    getpackagebase "$APP_NAME" "0" "APP_PKG_BASE"

    if [ -f "$APP_PKG_BASE/stop.sh" ]; then
        @go.log INFO "Using Package stop.sh information"
        . $APP_PKG_BASE/stop.sh
    else
        @go.log INFO "Using default stop script"
        stopsvc "RES" "$APP_MAR_ID" "$APP_MAR_FILE" "$MARATHON_SUBMIT"
    fi

}


_packagestop "$@"
