#!/bin/bash
#
# Stop  an already installed package
#
# Arguments:
#
sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$MAPR_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$PACKAGE_CONF"

reqshared "dockerregv2 zetaca openldap"

. "$_GO_USE_MODULES" 'libpackage'


function _packagestop() {

    MYDIR=$(pwd)

    UNATTEND="0"

  . /mapr/$CLUSTERNAME/zeta/kstore/env/zeta_shared.sh

    ACTION_SRC="user"
    for i in "$@"
        do
        case $i in
            *)
            CONF_FILE="$i"
            # unknown option
            ;;
        esac
    done

    if [ ! -f "$CONF_FILE" ]; then
        @go.log FATAL "You must specify a path to a conf file"
    fi

    . $CONF_FILE

    # Determine the package base
    getpackagebase "$APP_NAME" "0" "APP_PKG_BASE"


    if [ -f "$APP_PKG_BASE/stop.sh" ]; then
        @go.log INFO "Using Package stop.sh information"
        . $APP_PKG_BASE/stop.sh
    else
        CUR_STATUS=$(./zeta cluster marathon getinfo $APP_MAR_ID "ALL" $MARATHON_SUBMIT)
        EXISTS=$(echo $CUR_STATUS|grep "does not exist")

        if [ "$EXISTS" == "" ]; then
            RUNNING=$(echo $CUR_STATUS|grep "TASK_RUNNING")
            if [ "$RUNNING" != "" ]; then
                @go.log INFO "Scalling $APP_ID to 0 instances via $APP_MAR_ID"
                ./zeta cluster marathon scale $APP_MAR_ID 0 $MARATHON_SUBMIT 1
            else
                @go.log WARN "App $APP_ID is submitted to Marathon, but doesn't appear to be in a TASK_RUNNING state: Not Stopping - $CUR_STATUS"
            fi
        else
            @go.log WARN "The instance you specified, $APP_ID has not been submitted to Marathon yet, as Marathon reports it doesn't exist"
        fi
    fi

}


_packagestop "$@"
