#!/bin/bash
#
# Stop  an already installed package
#
# Arguments:
#
sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$PACKAGE_CONF"

reqshared "dockerregv2 zetaca openldap"

. "$_GO_USE_MODULES" 'libpackage'


function _packagestop() {

    MYDIR=$(pwd)

    UNATTEND="0"

  . $CLUSTERMOUNT/zeta/kstore/env/zeta_shared.sh

    ACTION_SRC="user"
    for i in "$@"
        do
        case $i in
            *)
            CONF_FILE="$i"
            # unknown option
            ;;
        esac
    done

    if [ ! -f "$CONF_FILE" ]; then
        @go.log FATAL "You must specify a path to a conf file"
    fi

    . $CONF_FILE

    # Determine the package base
    getpackagebase "$APP_NAME" "0" "APP_PKG_BASE"

    if [ -f "$APP_PKG_BASE/stop.sh" ]; then
        @go.log INFO "Using Package stop.sh information"
        . $APP_PKG_BASE/stop.sh
    else
        @go.log INFO "Using default start instance"
        if [ "$APP_MAR_FILE" != "DIRECTORY" ]; then
            stopsvc "RES" "$APP_MAR_ID" "$APP_MAR_FILE" "$MARATHON_SUBMIT"
            echo ""
        else
            if [ ! -d "$APP_MAR_DIR" ]; then
                @go.log FATAL "APP_MAR_FILE indicated a directory of marathon files, however, the directory $APP_MAR_DIR was not found"
            fi
            for MAR_FILE in $(ls -1 $APP_MAR_DIR); do
                MAR_ID=$(cat $MAR_FILE|grep "\"id\""|sed "s/\"id\"://g"|sed -r "s/ +//g"|sed -r "s/[\",]//g") 
                @go.log INFO "Stopping $MAR_ID"
                stopsvc "RES" "$MAR_ID" "$MAR_FILE" "$MARATHON_SUBMIT"
                echo ""
            done
        fi
    fi

}


_packagestop "$@"
