#!/bin/bash
# This script searches for cluster.conf files. It does not source or error our if cluster.conf is not found.
#
# First it checks for a CLUSTERNAME,
# If it does exist, it looks for /mapr/$CLUSTERNAME/zeta/kstore/cluster.conf and fills the CLUSTER_CONF variable
# If it doesn't exist it looks in /home/zetaadm/cluster.conf and if it does exist, it fills the CLUSTER_CONF variable
# If that doesn't exist, than leave the CLUSTER_CONF Variable blank
#
CLUSTERNAME=$(ls /mapr)
CLUSTER_CONF=""


if [ "$CLUSTERNAME" != "" ]; then
    if [ -f "/mapr/$CLUSTERNAME/zeta/kstore/cluster.conf" ]; then
        CLUSTER_CONF="/mapr/$CLUSTERNAME/zeta/kstore/cluster.conf"
    else
        if [ -f "./conf/cluster.conf" ]; then
            CLUSTER_CONF="./conf/cluster.conf"
        fi
    fi
else
    if [ -f "./conf/cluster.conf" ]; then
        CLUSTER_CONF="./conf/cluster.conf"
    fi
fi
