#!/bin/bash
#
# Open Ldap  helper fuctions for use with Zeta
#


#
# addgroup
# Adds a group to openldap
# Arguments:
# $1 = group name
# $2 = group id
# $3 = group role
# $4 = Group description
#
function addgroup() {

    GROUP_NAME=$1
    GROUP_ID=$2
    GROUP_ROLE=$3
    GROUP_DESC=$4

    if [ "$GROUP_DESC" == "" ]; then
        GROUP_DESC="No Description"
    fi

    LDIF_DATA="dn: cn=${GROUP_NAME},ou=groups,ou=zeta${GROUP_ROLE},${LDAP_BASE}"$'\n'
    LDIF_DATA="${LDIF_DATA}changetype: add"$'\n'
    LDIF_DATA="${LDIF_DATA}objectClass: top"$'\n'
    LDIF_DATA="${LDIF_DATA}objectClass: posixGroup"$'\n'
    LDIF_DATA="${LDIF_DATA}gidNumber: ${GROUP_ID}"$'\n'
    LDIF_DATA="${LDIF_DATA}description: ${GROUP_DESC}"$'\n'

    runldapcommand "$LDIF_DATA" "ADD"

}



function addindexcache(){
    IDX=$1
    IDX_TYPE=$2

    LDIF_DATA=""

    if [ "$IDX" == "UPDATECACHE" ]; then
        # Updating Cache Size of olcDbIDLcachesize
        LDIF_DATA="${LDIF_DATA}dn: olcDatabase={1}hdb,cn=config"$'\n'
        LDIF_DATA="${LDIF_DATA}changetype:modify"$'\n'
        LDIF_DATA="${LDIF_DATA}add: olcDbIDLcacheSize"$'\n'
        LDIF_DATA="${LDIF_DATA}olcDbIDLcacheSize: ${IDX_TYPE}"$'\n'
        LDIF_DATA="${LDIF_DATA}"$'\n'
        LDIF_DATA="${LDIF_DATA}dn: olcDatabase={1}hdb,cn=config"$'\n'
        LDIF_DATA="${LDIF_DATA}changetype:modify"$'\n'
        LDIF_DATA="${LDIF_DATA}add: olcDbCachesize"$'\n'
        LDIF_DATA="${LDIF_DATA}olcDbCachesize: ${IDX_TYPE}"$'\n'
    else
        # Adding Index
        LDIF_DATA="${LDIF_DATA}dn: olcDatabase={1}hdb,cn=config"$'\n'
        LDIF_DATA="${LDIF_DATA}changetype:modify"$'\n'
        LDIF_DATA="${LDIF_DATA}add: olcDbIndex"$'\n'
        LDIF_DATA="${LDIF_DATA}olcDbIndex: ${IDX} ${IDX_TYPE}"$'\n'
    fi

    LDAP_ROOT="$CLUSTERMOUNT/zeta/shared/openldap"
    LDIF_FILE_ZETA="${LDAP_ROOT}/slapd.d/tmp_index.ldif"
    LDIF_FILE_DOCKER="/etc/ldap/slapd.d/tmp_index.ldif"

    RUN_FILE_ZETA="${LDAP_ROOT}/slapd.d/run.sh"
    RUN_FILE_DOCKER="/etc/ldap/slapd.d/run.sh"


    ADD_CMD="ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f ${LDIF_FILE_DOCKER}"


cat > ${LDIF_FILE_ZETA} << EOLDIF
$LDIF_DATA
EOLDIF


cat > ${RUN_FILE_ZETA} << EOR
#!/bin/bash
echo "Adding Index $IDX in Docker Container"
echo ""
$ADD_CMD
echo ""
echo "Finished Adding Index $IDX"
echo ""
EOR
chmod +x ${RUN_FILE_ZETA}

UPDATE_FILE="./update_script.sh"

cat > ${UPDATE_FILE} << EOY
#!/bin/bash
CID=\$(sudo docker ps|grep openldap|cut -d" " -f1)
if [ "\$CID" == "" ]; then
    echo "Open Ldap not found on this host, INDEXES NOT ADDED!!!!"
    exit 1
fi
echo "Running script now in docker container"
echo ""
sudo docker exec \$CID ${RUN_FILE_DOCKER}
echo ""
echo "Finished Docker Exec"
echo ""
EOY
    chmod +x ${UPDATE_FILE}

    CURHOST=$(./zeta cluster marathon getinfo "shared/openldap" "host" "$MARATHON_SUBMIT")

#    OLDAP_ID="$MARATHON_SUBMIT/shared/openldap"
#    CURHOST=$(curl -s -X GET $OLDAP_ID/tasks|grep -o -P "\"host\":\"[^\"]+\""|cut -d":" -f2|sed "s/\"//g")

    @go.log INFO "Open LDAP Currently Running on Host: $CURHOST - Adding Indexes there"
    scp -o StrictHostKeyChecking=no update_script.sh $CURHOST:/home/$IUSER/
    ssh -o StrictHostKeyChecking=no $CURHOST "/home/$IUSER/update_script.sh && rm /home/$IUSER/update_script.sh"

    rm $UPDATE_FILE
    rm $RUN_FILE_ZETA
    rm $LDIF_FILE_ZETA

    @go.log INFO "Added Index $IDX to Open LDAP"
}


function adduser2group(){

    USER_NAME=$1
    GROUP_NAME=$2
    ROLE=$3

    if [ "$ROLE" == "" ]; then
        @go.log WARN "No Role specified in adduser2group function trying default of shared"
        ROLE="shared"
    fi
    DN="cn=$GROUP_NAME,ou=groups,ou=zeta$ROLE,$LDAP_BASE"

    LDIF_DATA="dn: $DN"$'\n'
    LDIF_DATA="${LDIF_DATA}changetype: modify"$'\n'
    LDIF_DATA="${LDIF_DATA}add: memberuid"$'\n'
    LDIF_DATA="${LDIF_DATA}memberuid: $USER_NAME"$'\n'

    runldapcommand "$LDIF_DATA" "MODIFY"
}



function adduser() {

    UNAME=$1
    UUID=$2
    FNAME=$3
    LNAME=$4
    ROLE=$5
    UHASH=$6


    LDIF_DATA="dn: cn=$UNAME,ou=users,ou=zeta$ROLE,$LDAP_BASE"$'\n'
    LDIF_DATA="${LDIF_DATA}changetype: add"$'\n'
    LDIF_DATA="${LDIF_DATA}objectClass: top"$'\n'
    LDIF_DATA="${LDIF_DATA}objectClass: posixAccount"$'\n'
    LDIF_DATA="${LDIF_DATA}objectClass: inetOrgPerson"$'\n'
    LDIF_DATA="${LDIF_DATA}cn: $UNAME"$'\n'
    LDIF_DATA="${LDIF_DATA}givenName: $FNAME"$'\n'
    LDIF_DATA="${LDIF_DATA}sn: $LNAME"$'\n'
    LDIF_DATA="${LDIF_DATA}uidNumber: $UUID"$'\n'
    LDIF_DATA="${LDIF_DATA}uid: $UNAME"$'\n'
    LDIF_DATA="${LDIF_DATA}gidNumber: 2501"$'\n'
    LDIF_DATA="${LDIF_DATA}homeDirectory: /home/$UNAME"$'\n'
    LDIF_DATA="${LDIF_DATA}loginShell: /bin/bash"$'\n'
    LDIF_DATA="${LDIF_DATA}userPassword: $UHASH"$'\n'

    runldapcommand "$LDIF_DATA" "MODIFY"


}

function hashpass() {

    local PASS2HASH=$1
    local RESULT=$2
    THASH=""
    runldapcommand "$PASS2HASH" "HASHPASS" "THASH"

    eval $RESULT="'$THASH'"
}

function setpass() {
    ROLE=$1
    UNAME=$2
    PASSHASH=$3



    LDIF_DATA="dn: cn=$UNAME,ou=users,ou=zeta$ROLE,$LDAP_BASE"$'\n'
    LDIF_DATA="${LDIF_DATA}changetype: modify"$'\n'
    LDIF_DATA="${LDIF_DATA}replace: userPassword"$'\n'
    LDIF_DATA="${LDIF_DATA}userPassword: $PASSHASS"$'\n'


    runldapcommand "$LDIF_DATA" "MODIFY"
}

function addou() {

    ROLE=$1
    OU=$2
    OUPREFIX=$3
    OUDESC=$4

    if [ "$OUDESC" == "" ]; then
        OUDESC="No Description"
    fi

    LDIF_DATA="dn: ${OUPREFIX},${LDAP_BASE}"$'\n'
    LDIF_DATA="${LDIF_DATA}changetype: add"$'\n'
    LDIF_DATA="${LDIF_DATA}ou: ${OU}"$'\n'
    LDIF_DATA="${LDIF_DATA}objectClass: top"$'\n'
    LDIF_DATA="${LDIF_DATA}objectClass: organizationalUnit"$'\n'
    LDIF_DATA="${LDIF_DATA}description: $OUDESC"$'\n'
    LDIF_DATA="${LDIF_DATA}"$'\n'

    runldapcommand "$LDIF_DATA" "ADD"

}

function retnextuid() {
    local RESULT=$1
    local MROLE=$2

    STARTUID=$(cat ./conf/zetasync/zetauid.list|grep $MROLE|cut -d":" -f2)

    if [ "$STARTUID" != "" ]; then
        ENDUID=$(( $STARTUID + 499999 ))

        @go.log INFO "Looking for next UID in role $MROLE with start UID of $STARTUID and end UID of $ENDUID"

        MAXUID="$STARTUID"

        runldapsearch "ALLUIDS" "-LLL -b \"dc=marathon,dc=mesos\" \"(uidNumber=*)\" uidNumber"

        JUSTUIDS=$(echo "$ALLUIDS"|grep uidNumber|sed "s/uidNumber: //g")

        for L in $JUSTUIDS; do
            if [ "$L" -ge "$STARTUID" ] && [ "$L" -lt "$ENDUID" ]; then
                if [ "$L" -ge "$MAXUID" ]; then
                    MAXUID=$(( $L + 1 ))
                fi
            fi
        done
    else
        @go.log FATAL "Role $MROLE Not Installed"
    fi
    eval $RESULT="'$MAXUID'"
}
function retnextgid() {
    local RESULT=$1
    local MROLE=$2

    STARTGID=$(cat ./conf/zetasync/zetauid.list|grep $MROLE|cut -d":" -f2)
    if [ "$STARTGID" != "" ]; then
        STARTGID=$(( $STARTGID + 500000 ))
        ENDGID=$(( $STARTGID + 499999 ))

        @go.log INFO "Looking for next GID in role $MROLE with start GID of $STARTGID and end GID of $ENDGID"

        MAXGID="$STARTGID"

        runldapsearch "ALLGIDS" "-LLL -b \"dc=marathon,dc=mesos\" \"(gidNumber=*)\" gidNumber"

        JUSTGIDS=$(echo "$ALLGIDS"|grep gidNumber|sed "s/gidNumber: //g")

        for L in $JUSTGIDS; do
            if [ "$L" -ge "$STARTGID" ] && [ "$L" -lt "$ENDGID" ]; then
                if [ "$L" -ge "$MAXGID" ]; then
                    MAXGID=$(( $L + 1 ))
                fi
            fi
        done
    else
        @go.log FATAL "Role $MROLE Not Installed"
    fi
    eval $RESULT="'$MAXGID'"
}

function runldapsearch(){
    local RESULT=$1
    local SEARCH=$2

    LDAP_ROOT="$CLUSTERMOUNT/zeta/shared/openldap"

    if [ ! -d "$LDAP_ROOT" ]; then
        @go.log FATAL "Open LDAP doesn't appear to be installed at $LDAP_ROOT"
    fi


    LDAPPASS=$(cat ${LDAP_ROOT}/initconf/default.yaml.startup|grep ADMIN|sed "s/LDAP_ADMIN_PASSWORD: //")

    APP_IMG="${ZETA_DOCKER_REG_URL}/ldaputils"

    buildldapclient

    TMP_LDIF="`pwd`/tmpldif"
    PASSFILE="${TMP_LDIF}/p.txt"
    TMPPASSFILE="${TMP_LDIF}/o.txt"
    LDIF_FILE="${TMP_LDIF}/tmpldif.ldif"

    mkdir -p $TMP_LDIF

    chmod -R 750 $TMP_LDIF
    touch $PASSFILE
    touch $TMPPASSFILE
    chmod 600 $PASSFILE
    chmod 600 $TMPPASSFILE

cat > $TMPPASSFILE << PWF
${LDAPPASS}
PWF
    cat $TMPPASSFILE|tr -d "\n" > $PASSFILE
    rm $TMPPASSFILE
    chmod 600 $PASSFILE

    RUN_CMD="ldapsearch -H ${LDAP_URL} -x -y /tmp/ldif/p.txt -D \"cn=admin,${LDAP_BASE}\" $SEARCH"

cat > ${TMP_LDIF}/runsearch.sh << ERUN
#!/bin/bash
$RUN_CMD
ERUN
    chmod +x ${TMP_LDIF}/runsearch.sh
    @go.log INFO "Running LDAP SEARCH - Type: SEARCH"
    DCKR="sudo docker run --rm -v=${TMP_LDIF}:/tmp/ldif:ro ${APP_IMG}"
    OUTSTR=$($DCKR /tmp/ldif/runsearch.sh)
    eval $RESULT="'$OUTSTR'"
    rm -rf $TMP_LDIF

}



function runldapcommand() {


    LDIF_CONTENTS=$1
    LDIF_COMMAND=$2
    PASSRESULT=$3

    LDAP_ROOT="$CLUSTERMOUNT/zeta/shared/openldap"

    if [ ! -d "$LDAP_ROOT" ]; then
        @go.log FATAL "Open LDAP doesn't appear to be installed at $LDAP_ROOT"
    fi


    LDAPPASS=$(cat ${LDAP_ROOT}/initconf/default.yaml.startup|grep ADMIN|sed "s/LDAP_ADMIN_PASSWORD: //")

    APP_IMG="${ZETA_DOCKER_REG_URL}/ldaputils"

    buildldapclient

    TMP_LDIF="`pwd`/tmpldif"
    PASSFILE="${TMP_LDIF}/p.txt"
    TMPPASSFILE="${TMP_LDIF}/o.txt"
    LDIF_FILE="${TMP_LDIF}/tmpldif.ldif"

    mkdir -p $TMP_LDIF

    chmod -R 750 $TMP_LDIF
    touch $PASSFILE
    touch $TMPPASSFILE
    chmod 600 $PASSFILE
    chmod 600 $TMPPASSFILE

cat > $TMPPASSFILE << PWF
${LDAPPASS}
PWF

    cat $TMPPASSFILE|tr -d "\n" > $PASSFILE
    rm $TMPPASSFILE
    chmod 600 $PASSFILE

cat > ${LDIF_FILE} << EOL
$LDIF_CONTENTS
EOL


    if [ "$LDIF_COMMAND" == "ADD" ]; then
        RUN_CMD="ldapadd -H ${LDAP_URL} -x -y /tmp/ldif/p.txt -D \"cn=admin,${LDAP_BASE}\" -f /tmp/ldif/tmpldif.ldif"
    elif [ "$LDIF_COMMAND" == "MODIFY" ]; then
        RUN_CMD="ldapmodify -H ${LDAP_URL} -x -y /tmp/ldif/p.txt -D \"cn=admin,${LDAP_BASE}\" -f /tmp/ldif/tmpldif.ldif"
    elif [ "$LDIF_COMMAND" == "HASHPASS" ]; then
        chmod 600 ${LDIF_FILE}
        echo -n "$LDIF_CONTENTS" > ${LDIF_FILE}
        RUN_CMD="slappasswd -T /tmp/ldif/tmpldif.ldif"
    else
        RUN_CMD="echo \"oops - command not found\""
    fi

cat > ${TMP_LDIF}/run.sh << ERUN
#!/bin/bash
$RUN_CMD
ERUN
    chmod +x ${TMP_LDIF}/run.sh
    @go.log INFO "Running LDAP Command - Type: $LDIF_COMMAND"
    DCKR="sudo docker run --rm -v=${TMP_LDIF}:/tmp/ldif:ro ${APP_IMG}"
    if [ "$LDIF_COMMAND" == "HASHPASS" ]; then
        PHASH=$($DCKR /tmp/ldif/run.sh)
        eval $PASSRESULT="'$PHASH'"
    else
        $DCKR /tmp/ldif/run.sh
    fi
    rm -rf $TMP_LDIF

}



#
# function buildldapclient
# If a ldaputils image doesn't exist, try to pull it and if that fails build it
#
function buildldapclient(){
 
    APP_IMG="${ZETA_DOCKER_REG_URL}/ldaputils"

    OUT=$(sudo docker images|grep ldaputils)
    if [ "$OUT" == "" ]; then
        sudo docker pull $APP_IMG
        OUT=$(sudo docker images|grep ldaputils)
        if [ "$OUT" == "" ]; then
            if [ "$DOCKER_PROXY" != "" ]; then
                DOCKER_LINE1="ENV http_proxy=$DOCKER_PROXY"
                DOCKER_LINE2="ENV HTTP_PROXY=$DOCKER_PROXY"
                DOCKER_LINE3="ENV https_proxy=$DOCKER_PROXY"
                DOCKER_LINE4="ENV HTTPS_PROXY=$DOCKER_PROXY"
                DOCKER_LINE5="ENV NO_PROXY=$DOCKER_NOPROXY"
                DOCKER_LINE6="ENV no_proxy=$DOCKER_NOPROXY"
            else
                DOCKER_LINE1=""
                DOCKER_LINE2=""
                DOCKER_LINE3=""
                DOCKER_LINE4=""
                DOCKER_LINE5=""
                DOCKER_LINE6=""
            fi


             mkdir -p ./tmp
cat > ./tmp/Dockerfile << EOF
FROM ubuntu:xenial
$DOCKER_LINE1
$DOCKER_LINE2
$DOCKER_LINE3
$DOCKER_LINE4
$DOCKER_LINE5
$DOCKER_LINE6
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y ldap-utils curl slapd ca-certificates && rm -f /usr/local/share/ca-certificates/zetaroot.crt && update-ca-certificates -f && curl -o /usr/local/share/ca-certificates/zetaroot.crt http://zetaca-shared.marathon.slave.mesos:10443/cacert && update-ca-certificates
CMD ["/bin/bash"]
EOF

            cd ./tmp
            sudo docker build -t ${APP_IMG} .
            sudo docker push ${APP_IMG}
            cd ..
            rm -rf ./tmp
        fi

    fi
}

