#!/bin/bash
#
# This script uses the find cluster conf script to determine if there is CLUSTER_CONF and sources it if it exists, and errors if it does not.
# 3.1 Display error that cluster.conf does not exist and needs to exist before ./zeta will work - Exit (w/ Error)

. "$_GO_USE_MODULES" 'findclusterconf'

if [ "${CLUSTER_CONF}" != "" ]; then
    echo "Sourcing $CLUSTER_CONF"
    . $CLUSTER_CONF
else
    echo "No cluster.conf found: exiting"
    exit 1
fi


