#!/bin/bash
#
# cluster - Scripts to stage and run Zeta cluster installs
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"

function _cluster() {

    LOCK="0"

    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$CLUSTER_CONF"

    echo ""
    echo "********************************"
    echo "Scripts should now be run on cluster"
    echo "That should be: $INIT_NODE"
    echo "********************************"
    echo ""
    echo "Sub Commands to use with cluster:"
    echo "./zeta cluster marathon  - Scripts for interfacing with Marathon"
    echo "./zeta cluster zetaca  - Scripts for interfacing with zetaca"
    echo ""
    echo "Cluster specfic tasks: (These all should be run once in this order)"
    echo "./zeta cluster zetabase - Install base Zeta filesystem layout (must have Fuse from FS package Installed on all nodes)"
    echo "./zeta cluster shareddocker  - Install a Shared Docker registry on the cluster"
    echo "./zeta cluster sharedldap - Install a shared OpenLDAP server on the cluster"
    echo "./zeta cluster allldaphosts - Update all hosts in prep.conf to use OpenLDAP"
    echo "./zeta cluster addsharedrole - Runs the role add script for the shared role"
    echo "./zeta cluster sharedldapadmin - Install a shared Ldap Admin Server on the cluster"
    echo "./zeta cluster ldapperf -a -u - Update Ldap Server for increased performance run with -a flag"
    echo ""
    echo "Helper Scripts:"
    echo "./zeta cluster hostldapupdate - Update a single host to use OpenLDAP"
    echo "./zeta cluster addzetarole - Create role users, directories, and shared files for a single role with -r="
    echo ""
    echo "Config Management:"
    echo "./zeta cluster -l  #lock or unlockcluster.conf file"
    echo ""


    if [ "$LOCK" == "1" ]; then
       lockconf "$CLUSTER_CONF"
    fi

}

_cluster "$@"

