#!/bin/bash
#
# cluster - Scripts to stage and run Zeta cluster installs
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$MAPR_CONF"

function _cluster() {

    LOCK="0"
    UNLOCK="0"

    for i in "$@"
    do
    case $i in
        -u|--unlockconf)
        UNLOCK="1"
        ;;
        -l|--lockconf)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    if [ "$UNLOCK" == "1" ] && [ "$LOCK" == "1" ]; then
        @go.log FATAL "Both Lock (-l) and Unlock (-u) cannot be specified at the same time"
    fi

    initconf "$CLUSTER_CONF"

    echo ""
    echo "********************************"
    echo "Scripts should now be run on cluster"
    echo "That should be: $INIT_NODE"
    echo "********************************"
    echo ""
    echo "Sub Commands to use with cluster:"
    echo "./zeta cluster marathon  - Scripts for interfacing with Marathon"
    echo "./zeta cluster zetaca  - Scripts for interfacing with zetaca"
    echo ""
    echo "Cluster specfic tasks:"
    echo "./zeta cluster zetabase - Install base Zeta filesystem layout (must have MapR/Fuse Installed on all nodes)"
    echo "./zeta cluster shareddocker  - Install a Shared Docker registry on the cluster"
    echo "./zeta cluster sharedldap - Install a shared OpenLDAP server on the cluster"
    echo "./zeta cluster allldaphosts - Update all hosts in prep.conf to use OpenLDAP"
    echo "./zeta cluster sharedldapadm - Install a shared Ldap Admin Server on the cluster"
    echo ""
    echo "Helper Scripts:"
    echo "./zeta cluster hostldapupdate - Update a single host to use OpenLDAP"
    echo ""
    echo "Config Management:"
    echo "./zeta cluster -l|--lockconf Lock cluster.conf file"
    echo "./zeta cluster -u|--unlockconf Unlock cluster.conf file"
    echo ""


    if [ "$UNLOCK" == "1" ] || [ "$LOCK" == "1" ]; then
       lockconf "$CLUSTER_CONF"
    fi

}

_cluster "$@"

