#!/bin/bash
#
# cluster - Scripts to stage and run Zeta cluster installs
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$MAPR_CONF"

function _cluster() {

    LOCK="0"
    UNLOCK="0"

    for i in "$@"
    do
    case $i in
        -u|--unlockconf)
        UNLOCK="1"
        ;;
        -l|--lockconf)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    if [ "$UNLOCK" == "1" ] && [ "$LOCK" == "1" ]; then
        @go.log FATAL "Both Lock (-l) and Unlock (-u) cannot be specified at the same time"
    fi

    initconf "$CLUSTER_CONF"

    echo ""
    echo "********************************"
    echo "Scripts should now be run on cluster"
    echo "That should be: $INIT_NODE"
    echo "********************************"
    echo ""
    echo "Commands to use with cluster:"
    echo "./zeta cluster -l|--lockconf Lock cluster.conf file"
    echo "./zeta cluster -u|--unlockconf Unlock cluster.conf file"
    echo ""


    if [ "$UNLOCK" == "1" ] || [ "$LOCK" == "1" ]; then
       lockconf "$CLUSTER_CONF"
    fi

}

_cluster "$@"

