#!/bin/bash
#
# dcos - Scripts to stage and use DCOS on a Zeta Cluster
#
#

sourceconf "$PREP_CONF"

function _dcos() {

    LOCK="0"

    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$DCOS_CONF"

    echo ""
    echo "********************************"
    echo "It is highly advised to run the DCOS Scripts on the cluster initial node specified in the prep stage"
    echo "That should be: $INIT_NODE"
    echo "********************************"
    echo ""
    echo "Commands to use with dcos:"
    echo ""
    echo "./zeta dcos bootstrap         # Create DCOS config and bootstrap on bootstrap node"
    echo "./zeta dcos install -n=NODE1  # Install DCOS on NODE1 given dcos.conf"
    echo "./zeta dcos install -a        # Install DCOS on all nodes listed in dcos.conf"
    echo "./zeta dcos install -a -u     # Install DCOS on all nodes listed in dcos.conf and do so unattended"
    echo ""
    echo "./zeta dcos -l                # Lock or unlock dcos.conf file"
    echo ""


    if [ "$LOCK" == "1" ]; then
       lockconf "$DCOS_CONF"
    fi

}

_dcos "$@"

