#!/bin/bash
#
# dcos - Scripts to stage and use DCOS on a Zeta Cluster
#
#

. "$_GO_USE_MODULES" 'initconf'

function _dcos() {

    LOCK="0"
    UNLOCK="0"

    for i in "$@"
    do
    case $i in
        -u|--unlockconf)
        UNLOCK="1"
        ;;
        -l|--lockconf)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    if [ "$UNLOCK" == "1" ] && [ "$LOCK" == "1" ]; then
        @go.log FATAL "Both Lock (-l) and Unlock (-u) cannot be specified at the same time"
    fi

    initconf "$DCOS_CONF"

    echo ""
    echo "********************************"
    echo "It is highly advised to run the DCOS Scripts on the cluster initial node specified in the prep stage"
    echo "That should be: $INIT_NODE"
    echo "********************************"
    echo ""
    echo "Commands to use with dcos:"
    echo ""
    echo "./zeta dcos boostrap - Create DCOS config and bootstrap on bootstrap node"
    echo "./zeta dcos install %NODE - Install DCOS on %NODE given dcos.conf"
    echo "./zeta dcos install --all - Install DCOS on all nodes listed in dcos.conf"
    echo "./zeta dcos -l|--lockconf Lock dcos.conf file"
    echo "./zeta dcos -u|--unlockconf Unlock dcos.conf file"
    echo ""


    if [ "$UNLOCK" == "1" ] || [ "$LOCK" == "1" ]; then
       lockconf "$PREP_CONF"
    fi

}

_dcos "$@"

