#!/bin/bash
#
# ./zeta network
#
# Helps to maintain networks in a zeta environment
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"

function _network() {
   LOCK="0"

    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$NETWORK_CONF"

    echo ""
    echo "********************************"
    echo "Network Administration Scripts for Zeta"
    echo "********************************"
    echo ""
    echo "Commands to use with package:"
    echo ""
    echo "./zeta network                          # This command"
    echo "./zeta network deployfw                 # Calls createfw and then deploys to all nodes"
    echo "./zeta network createfw                 # Creates the current FW for nodes"
    echo ""
    echo "./zeta network -l                # Lock or unlock package.conf file"
    echo ""

    if [ "$LOCK" == "1" ]; then
       lockconf "$NETWORK_CONF"
    fi


}

_network "$@"



