#!/bin/bash
#
# ./zeta node
#
# Help with administration of nodes in Zeta Environment
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"



function _node() {
   LOCK="0"

    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$NODE_CONF"

    echo ""
    echo "********************************"
    echo "Node Management Scripts for Zeta"
    echo "********************************"
    echo ""
    echo "Commands to use with package:"
    echo ""
    echo "./zeta node                          # This command"
    echo "./zeta node status                   # Status of Nodes"
    echo ""
    echo "./zeta node -l                # Lock or unlock node.conf file"
    echo ""

    if [ "$LOCK" == "1" ]; then
       lockconf "$NODE_CONF"
    fi


}

_node "$@"



