#!/bin/bash
#
# ./zeta package
#
# Helps to maintain packages in a zeta environment
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$MAPR_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"

reqshared "dockerregv2 zetaca openldap"


function _package() {
   LOCK="0"

    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$PACKAGE_CONF"

    echo ""
    echo "********************************"
    echo "Package Installation Scripts for Zeta"
    echo "********************************"
    echo ""
    echo "Commands to use with package:"
    echo ""
    echo "./zeta package                #"
    echo ""
    echo "./zeta package -l                # Lock or unlock package.conf file"
    echo ""

    if [ "$LOCK" == "1" ]; then
       lockconf "$PACKAGE_CONF"
    fi


}

_package "$@"



