#!/bin/bash
#
# prep works to take list of nodes (looking in ./conf/hostlist.txt" and get them ready fo DCOS and Zeta
# There are a number of items this command looks to do and it's broken up into two child commands
#
# Child Commands
# prep genkey - Generate a SSH key for use between nodes. This is particularly handy in AWS but could be made to work on prem too
# prep ubuntu - Install Docker, patches, etc, for use with an Ubuntu 16.04 install
# prep centos - Install Docker, patches, etc, for use with CentOS install
#

PREP_CONF="./conf/prep_conf.conf"
#
# Check for the the conf and offer to create one
# Arguments: if --all is passed then this script will not only create the prep_conf.conf, but all run it all of the nodes in the node list
#
function _prep() {
    ALL=$1
    ATONCE=$2

    if [ -f "$PREP_CONF" ]; then
        echo "There is a current prep_conf.conf file already in the conf folder"
        echo "Do you wish to replace this prep_conf.conf?"
        read -e -p "(R)eplace, (U)se, or (E)xamine prep.conf? " -i "E" EXIST_PREP
        if [ "$EXIST_PREP" == "E" ]; then
            ./zeta prep display
            echo ""
            read -e -p "(R)eplace or (U)se existing prep_conf.conf? " -i "U" EXIST_PREP
        fi
    else
        EXIST_PREP="R"
    fi

    if [ "$EXIST_PREP" == "R" ]; then
        ./zeta prep createprepconf
    fi
    . $PREP_CONF
    echo ""
    echo "Commands to use with prep:"
    echo ""
    echo "./zeta prep userprep %NODE - Prep user on a specific node"
    echo "./zeta prep systemprep %NODE - Prep system on a specific node"
    echo "./zeta prep --all - Prep User and system on all nodes"
    echo ""
    if [ "$ALL" == "--all" ]; then
        for NODE in $NODES; do
            ./zeta prep userprep $NODE
            if [ "$ATONCE" == "-p" ]; then
                ./zeta prep systemprep $NODE -p
            else
                ./zeta prep systemprep $NODE
            fi
        done
        echo "To log into the initial node, please use:"
        echo ""
        echo "ssh -i $OUT_KEY zetaadm@$INIT_NODE"
        echo ""
    fi
}

_prep "$@"

