#!/bin/bash
#
# The prep scripts look to install users and certain required system packages on new nodes for Zeta Architecture
#
# Child Commands
# prep genkey - Generate a SSH key for use between nodes. This is particularly handy in AWS but could be made to work on prem too
#
#
# Check for the the conf and offer to create one
# Arguments:
#     -l|--lock        Lock the config so it no longer prompts if you want to use the existing config
#

function _prep() {

    LOCK="0"

    for i in "$@"
    do
    case $i in
        -l|--lockconf)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$PREP_CONF"

    echo "Commands to use with prep:"
    echo ""
    echo "./zeta prep userprep -n=NODE     # Prep user on a specific node"
    echo "./zeta prep systemprep -n=NODE   # Prep system on a specific node"
    echo "./zeta prep install -n=NODE1     # Run both the userprep and systemprep on NODE1"
    echo "./zeta prep install -a           # Prep User and system on all nodes but do so one at a time"
    echo "./zeta prep install -a -u        # Prep all nodes in prep.conf in parallel"
    echo ""
    echo ""
    echo "To lock or unlock the prep config:"
    echo "./zeta prep -l"
    echo ""
    echo ""
    echo "To log into the initial node, please use:"
    echo ""
    echo "ssh -i $OUT_KEY ${IUSER}@$INIT_NODE"
    echo ""


    if [ "$LOCK" == "1" ]; then
       lockconf "$PREP_CONF"
    fi

}

_prep "$@"

