#!/bin/bash
#
# ./zeta role
#
# Help with administration of roles in Zeta Environment
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"
sourceconf "$NODE_CONF"

reqshared "dockerregv2 zetaca openldap"


function _role() {
   LOCK="0"

    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$ROLE_CONF"

    echo ""
    echo "********************************"
    echo "Package Installation Scripts for Zeta"
    echo "********************************"
    echo ""
    echo "Commands to use with package:"
    echo ""
    echo "./zeta roles                          # This command"
    echo "./zeta roles status                   # Status of Nodes"
    echo ""
    echo "./zeta role -l                # Lock or unlock role.conf file"
    echo ""

    if [ "$LOCK" == "1" ]; then
       lockconf "$ROLE_CONF"
    fi


}

_node "$@"



