#!/bin/bash
#
# ./zeta zk
#
# Provides and easy interface to various ZK servers on the cluster
#
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$NETWORK_CONF"
sourceconf "$FS_CONF"
sourceconf "$FS_PROVIDER_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"
sourceconf "$CLUSTER_BASE_CONF"

reqshared "dockerregv2 zetaca openldap"


function _zk() {
   LOCK="0"

    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$ZK_CONF"

    echo ""
    echo "*****************************************"
    echo "Zookeeper Administration Scripts for Zeta"
    echo "*****************************************"
    echo ""
    echo ""
    echo "Common options for ZK Commands"
    echo ""
    echo "-j                                      # JSON output mode (default is txt mode)"
    echo "-r                                      # Recurse. For certain commands (list delete create) do them recursively"
    echo "-s                                      # Silent mode, supress all warning/info just show results"
    echo "-u                                      # For operations that change (remove/create/update etc) perform the request action without a prompt "
    echo "-c=\"node1:port,node2:port,node3:port\"   # Manually specify ZK cluster to connect to (instead of using Zeta ZK Reference"
    echo "-z=ZK_REF                               # Use refernce to identify ZK cluster to connect to (MESOS and FS are common, more specified in zk.conf. Defaults to ZK_DEFAULT in zk.conf)"
    echo ""
    echo "Commands to use with zeta zk:"
    echo ""
    echo "./zeta zk                               # This command"
    echo "./zeta zk buildzk                       # Builds the Zookeeper docker file and pushes to the cluster registry (No options for this command)"
    echo "./zeta zk list %NODE%                   # Lists a ZK Node %NODE% (/ if nothing passed)"
    echo "./zeta zk get %NODE%                    # Gets values for a ZK Node %NODE% (%NODE% Required)"
    echo ""
    echo "./zeta zk -l                            # Lock or unlock zk.conf file"
    echo ""

    if [ "$LOCK" == "1" ]; then
       lockconf "$ZK_CONF"
    fi



}



_zk
