#!/bin/bash
#
# mapr installmapr 
# Install mapr on all nodes in conf
#

sourceconf "$PREP_CONF"
sourceconf "$DCOS_CONF"
sourceconf "$MAPR_CONF"
sourceconf "$CLUSTER_CONF"
sourceconf "$CLUSTER_ZETACA_CONF"

MYDIR=$(pwd)

MEUSER=$(whoami)

if [ "$MEUSER" != "zetaadm" ]; then
    @go.log FATAL "This script needs to be un as zetaadm. Current User: $MEUSER"
fi

UNATTEND="0"

for i in "$@"
    do
    case $i in
        -u)
        UNATTEND="1"
        ;;
        *)
            # unknown option
        ;;
    esac
done

@go.log INFO "Creating Conf files for all nodes in mapr.conf"
echo ""
OLDIFS=$IFS
IFS=";"
for NODE in $INODES; do
    NODE_HOST=$(echo $NODE|cut -d":" -f1)
    NODE_DISKS=$(echo $NODE|cut -d":" -f2)
    @go.log INFO "Node Host: $NODE_HOST - Node Disks: $NODE_DISKS"
    echo ""
    if [ "$UNATTEND" == "1" ]; then
        ./zeta mapr installmaprnode -n="${NODE_HOST}" -d="${NODE_DISKS}" -u
    else
        ./zeta mapr installmaprnode -n="${NODE_HOST}" -d="${NODE_DISKS}"
    fi
done
IFS=$OLDIFS

echo "Starting CLDB Nodes"
IFS=","
STARTED=""
for CLDB in $CLDBS; do
    CLDB_HOST=$(echo $CLDB|cut -d":" -f1)
    STARTED="$STARTED $CLDB_HOST"
    ./zeta mapr submitmaprnode $CLDB_HOST
done
echo ""
echo ""



CLDBTEST=""
while [ "$CLDBTEST" == "" ]; do
    @go.log INFO "Waiting 20 seconds to check again for CLDB Nodes up"
    sleep 20
    for H in $STARTED; do
        @go.log INFO "Checking CLDB Node: $H"
        CLDBTEST=$(curl -s -k https://$H:8443)
        if [ "$CLDBTEST" != "" ]; then
            break
        fi
    done
done
@go.log INFO "CLDB Appears up and running"

IFS=";"
for NODE in $INODES; do
    NODE_HOST=$(echo $NODE|cut -d":" -f1)
    CHK=$(echo $STARTED|grep $NODE_HOST)
    if [ "$CHK" == "" ]; then
        ./zeta mapr submitmaprnode $NODE_HOST
        echo ""
    fi
done

echo ""
echo ""
IFS=$OLDIFS
